Jx().$package("alloy.appconfig",function(b){
		var d=this,
			c=b.event,
			e=b.localStorage,
			d=this,
			g=!1,
			j=!1,
			l=0,
			q=0,
			u=0,
			p=0;
		this.appConfigList={};
		this.appTempList={};
		this.systemConfigList={
			50:{
				id:50,
				appUrl:"",
				appName:"QQ",
				al:null,
				category:7,
				iconUrl:"111",
				"New Property":"Value..",
				minWidth:"260",
				width:"280",
				settingCenter:"0",
				windowMode:"none",
				ipadincompatible:0,
				provider:"Tencent \u817e\u8baf",
				ver:"2.3",
				alterMode:"",
				flashMode:"",
				appDesc:"WebQQ\u662f\u7531Tencent\u63d0\u4f9b\u7684\u7f51\u9875IM\u670d\u52a1\uff0c\u652f\u6301\u5728\u7ebf\u804a\u5929\u3001\u4f20\u8f93\u6587\u4ef6\u3001\u622a\u56fe\u3001\u6d88\u606f\u8bb0\u5f55\u6f2b\u6e38\u7b49\u591a\u79cd\u529f\u80fd\u3002",
				height:"560",
				loginLevel:"1",
				defaultMode:"",
				cannotUninstall:"1",
				powerLevel:"3",
				reportName:"eqq",
				appType:1
			},
			taskBar:{
				id:"taskBar",
				appName:"\u4efb\u52a1\u680f",
				appType:1,
				appLevel:"system",
				js:"./js/qqweb.system.module.js",
				windowMode:"none",
				customLoginValidate:!0,
				settingCenter:0
			},
			dock:{
				id:"dock",
				appName:"dock",
				appType:1,
				appLevel:"system",
				css:"./module/dock/style.css",
				js:"./module/dock/main.js",
				windowMode:"none"
			},
			tips:{
				id:"tips",
				appName:"tips",
				appType:1,
				appLevel:"system",
				js:"./js/qqweb.system.module.js",
				windowMode:"none",
				customLoginValidate:!1,
				settingCenter:0
			},
			shareComponent:{
				id:"shareComponent",
				appName:"shareComponent",
				appType:1,
				appLevel:"system",
				js:"./module/sharecomponent/main.js",
				css:"./module/sharecomponent/style.css",
				windowMode:"none",
				customLoginValidate:!1,
				settingCenter:0
			},
			helper:{
				id:"helper",
				appName:"WebQQ\u5c0f\u52a9\u624b",
				appName:"Q+ Web\u5c0f\u52a9\u624b",
				appType:1,
				appLevel:"system",
				css:"./module/helper/style.css",
				js:"./module/helper/main.js",
				width:358,
				height:230,
				right:5,
				bottom:5,
				hasCloseButton:!0,
				settingCenter:0
			},
			bubbleTip:{
				id:"bubbleTip",
				appName:"\u6c14\u6ce1\u63d0\u793a",
				appType:1,
				appLevel:"system",
				css:"./module/bubbletip/qqweb.app.bubbletip.css",
				js:"./module/bubbletip/qqweb.app.bubbletip.js",
				windowMode:"none"
			},
			qqWebIme:{
				id:"qqWebIme",
				appName:"QQ\u4e91\u8f93\u5165\u6cd5",
				appType:1,
				appLevel:"system",
				css:"./module/qqwebime/style.css",
				js:"./module/qqwebime/main.js",
				windowMode:"none",
				customLoginValidate:!1,
				click2run:1,
				quickPanelIcon:"./style/images/pinyin.png",
				settingCenter:0
			},
			qqHandWrite:{
				id:"qqHandWrite",
				appName:"QQ\u4e91\u624b\u5199\u677f",
				appType:2,
				appLevel:"system",
				appUrl:qqweb.CONST.MAIN_URL+"module/qqhandwrite/qqhandwrite.html?"+qqweb.CONST.UPDATE_TIME_STAMP,
				hasCloseButton:!0,
				hasMaxButton:!1,
				hasMinButton:!1,
				modeSwitch:!1,
				resize:!1,
				width:445,
				height:292,
				right:1,
				bottom:1,
				hasToolBar:0,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE
			},
			qqWebDict:{
				id:"qqWebDict",
				appName:"QQ\u4e91\u8bcd\u5178",
				appType:1,
				appLevel:"system",
				css:"./module/qqwebdict/style.css",
				js:"./module/qqwebdict/main.js",
				windowMode:"none",
				customLoginValidate:!1,
				settingCenter:0
			},
			appBar:{
				id:"appBar",
				appName:"appBar",
				appType:1,
				appLevel:"system",
				css:"./module/appbar/qqweb.app.appbar.css",
				js:"./module/appbar/qqweb.app.appbar.js",
				windowMode:"none",
				settingCenter:0
			},
			appMarket:{
				id:"appMarket",
				appName:"\u5e94\u7528\u5e02\u573a",
				appType:2,
				appDesc:"\u5e94\u7528\u5e02\u573a\u662fWebQQ\u7ed9\u7f51\u53cb\u6dfb\u52a0\u5e94\u7528\u7684\u5e73\u53f0\uff0c\u63d0\u4f9b\u6700\u70ed\uff0c\u6700\u65b0\u7684\u5e94\u7528\uff0c\u7f51\u53cb\u5206\u4eab\u4e5f\u5c3d\u5728\u5176\u4e2d\u3002",
				appDesc:"\u5e94\u7528\u5e02\u573a\u662fQ+ Web\u7ed9\u7f51\u53cb\u6dfb\u52a0\u5e94\u7528\u7684\u5e73\u53f0\uff0c\u63d0\u4f9b\u6700\u70ed\uff0c\u6700\u65b0\u7684\u5e94\u7528\uff0c\u7f51\u53cb\u5206\u4eab\u4e5f\u5c3d\u5728\u5176\u4e2d\u3002",
				appLevel:"system",
				appUrl:qqweb.CONST.MAIN_URL+"module/appmarket/appmarket.html?"+qqweb.CONST.UPDATE_TIME_STAMP,
				hasCloseButton:!0,
				hasMinButton:!0,
				hasMaxButton:!0,
				modeSwitch:!0,
				resize:!0,
				width:900,
				height:570,
				hasToolBar:0,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,quickPanel:1,
				titleIcon:"http://0.web.qstatic.com/webqqpic/style/images/appmarket_icon.png",
				quickPanelIcon:"./style/images/appmarket.png?20111011001",
				settingCenter:0
			},
			notifications:{
				id:"notifications",
				appName:"\u901a\u77e5\u8bbe\u7f6e",
				appType:1,
				appLevel:"system",
				css:"./module/notifications/qqweb.app.notifications.css",
				js:"./module/notifications/qqweb.app.notifications.js",
				hasMinButton:!1,
				hasMaxButton:!1,
				hasOkButton:!0,
				hasCancelButton:!0,
				hasToolBar:0,
				settingCenter:0
			},
			themeSetting:{
				id:"themeSetting",
				appName:"\u4e3b\u9898\u8bbe\u7f6e",
				appType:1,
				appLevel:"system",
				css:"./module/themesetting/qqweb.app.themesetting.css",
				js:"./module/themesetting/qqweb.app.themesetting.js",
				hasMinButton:!1,
				hasMaxButton:!1,
				hasToolBar:0,
				resize:!1,
				settingCenter:0
			},
			themeSetting2:{
				id:"themeSetting2",
				appName:"\u4e3b\u98982",
				appType:1,
				appLevel:"system",
				css:"./module/themesetting2/qqweb.app.themesetting2.css",
				js:"./module/themesetting2/qqweb.app.themesetting2.js",
				hasMinButton:!1,
				hasMaxButton:!1,
				hasToolBar:0,
				resize:!1,
				windowMode:"none",
				settingCenter:0
			},
			notifySetting:{
				id:"notifySetting",
				appName:"QQ\u63d0\u9192",
				appType:1,
				appLevel:"system",
				css:"./module/notifysetting/qqweb.app.notifysetting.css",
				js:"./module/notifysetting/qqweb.app.notifysetting.js",
				hasMinButton:!1,
				hasMaxButton:!1,
				hasOkButton:!0,
				hasCancelButton:!0,
				resize:!1,
				hasToolBar:0,
				settingCenter:0
			},
			desktopSetting:{
				id:"desktopSetting",
				appName:"\u684c\u9762\u8bbe\u7f6e",
				appType:1,
				appLevel:"system",
				css:"./module/desktopsetting/style.css",
				js:"./module/desktopsetting/main.js",
				hasMinButton:!1,
				hasMaxButton:!1,
				hasOkButton:!0,
				hasCancelButton:!0,
				resize:!1,
				minWidth:600,
				minHeight:450,
				hasToolBar:0,
				settingCenter:0
			},
			hotkeySetting:{
				id:"hotkeySetting",
				appName:"\u70ed\u952e",
				appType:1,
				appLevel:"system",
				css:"./module/hotkeysetting/qqweb.app.hotkeysetting.css",
				js:"./module/hotkeysetting/qqweb.app.hotkeysetting.js",
				hasMinButton:!1,
				hasMaxButton:!1,
				hasOkButton:!0,
				hasCancelButton:!0,
				resize:!1,
				hasToolBar:0,
				settingCenter:0
			},
			ienotification:{
				id:"ienotification",
				appType:1,
				appLevel:"system",
				appName:"IE\u6d88\u606f\u63d0\u9192",
				css:"./module/ienotification/qqweb.app.ienotification.css",
				js:"./module/ienotification/qqweb.app.ienotification.js",
				windowMode:"none"
			},
			msgBubble:{
				id:"msgBubble",
				appType:1,
				appLevel:"system",
				appName:"\u6d88\u606f\u8d70\u9a6c\u706f",
				css:"./module/messagebubble/qqweb.app.msgbubble.css",
				js:"./module/messagebubble/qqweb.app.msgbubble.js",
				windowMode:"none",
				settingCenter:0
			},
			messageManager:{
				id:"messageManager",
				appType:1,
				appLevel:"system",
				appName:"\u6d88\u606f\u7ba1\u7406\u5668",
				css:"./module/messagemanager/style.css",
				js:"./module/messagemanager/main.js",
				windowMode:"none"
			},
			chatLogViewer:{
				id:"chatLogViewer",
				appName:"\u804a\u5929\u8bb0\u5f55\u7ba1\u7406\u5668",
				appDesc:"WebQQ\u4e3a\u60a8\u63d0\u4f9b\u7684\u7fa4\u804a\u5929\u8bb0\u5f55\u6f2b\u6e38\u670d\u52a1\uff0c\u652f\u6301\u67e5\u770b7\u5929\u5185\u7fa4\u5185\u6d88\u606f\uff0c\u8fd8\u53ef\u4ee5\u76f4\u63a5\u4ece\u804a\u5929\u8bb0\u5f55\u91cc\u548c\u7fa4\u53cb\u53d1\u8d77\u4e34\u65f6\u4f1a\u8bdd\uff0c\u8d76\u5feb\u6765\u4f53\u9a8c\u5427\uff01",
				appDesc:"Q+ Web\u4e3a\u60a8\u63d0\u4f9b\u7684\u7fa4\u804a\u5929\u8bb0\u5f55\u6f2b\u6e38\u670d\u52a1\uff0c\u652f\u6301\u67e5\u770b7\u5929\u5185\u7fa4\u5185\u6d88\u606f\uff0c\u8fd8\u53ef\u4ee5\u76f4\u63a5\u4ece\u804a\u5929\u8bb0\u5f55\u91cc\u548c\u7fa4\u53cb\u53d1\u8d77\u4e34\u65f6\u4f1a\u8bdd\uff0c\u8d76\u5feb\u6765\u4f53\u9a8c\u5427\uff01",
				appType:1,
				appLevel:"system",
				css:"./module/chatlogviewer/qqweb.app.chatlogviewer.css",
				js:"./module/chatlogviewer/qqweb.app.chatlogviewer.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_ALL,
				windowMode:"multi",
				needApp:["eqq"],
				settingCenter:0
			},
			userDetails:{
				id:"userDetails",
				appName:"\u8be6\u7ec6\u8d44\u6599",
				appType:1,
				appLevel:"system",
				css:"./module/userdetails/qqweb.app.userdetails.css",
				js:"./module/userdetails/qqweb.app.userdetails.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_NOCHAT,
				windowMode:"multi",
				hasToolBar:0,
				needApp:["eqq"],
				settingCenter:0
			},
			avatarChanger:{
				id:"avatarChanger",
				appName:"\u66f4\u6362\u5934\u50cf",
				appType:1,
				appLevel:"system",
				css:"./module/avatarchanger/qqweb.app.avatarchanger.css",
				js:"./module/avatarchanger/qqweb.app.avatarchanger.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_NOCHAT,
				needApp:["eqq"],
				width:550,
				windowType:"EqqWindow",
				height:395,
				resize:!1,
				hasMinButton:!1,
				hasMaxButton:!1,
				hasOkButton:!0,
				hasCancelButton:!0,
				hasToolBar:0,
				settingCenter:0
			},
			groupDetails:{
				id:"groupDetails",
				appName:"\u7fa4\u8be6\u7ec6\u8d44\u6599",
				appType:1,
				appLevel:"system",
				css:"./module/groupdetails/qqweb.app.groupdetails.css",
				js:"./module/groupdetails/qqweb.app.groupdetails.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_NOCHAT,
				windowMode:"multi",
				hasToolBar:0,
				needApp:["eqq"],
				settingCenter:0
			},
			groupSystemMsg:{
				id:"groupSystemMsg",
				appName:"\u7fa4\u7cfb\u7edf\u6d88\u606f",
				appType:1,
				appLevel:"system",
				css:"./module/groupsystemmsg/qqweb.app.groupsystemmsg.css",
				js:"./module/groupsystemmsg/qqweb.app.groupsystemmsg.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_NOCHAT,
				windowMode:"multi",
				hasToolBar:0,
				windowType:"EqqWindow",
				needApp:["eqq"],
				settingCenter:0
			},
			appIntroduce:{
				id:"appIntroduce",
				appType:1,
				appName:"\u5e94\u7528\u4ecb\u7ecd",
				appLevel:"system",
				appDesc:"\u5728\u8fd9\u91cc\uff0c\u5e94\u7528\u4ecb\u7ecd",
				provider:"Tencent \u817e\u8baf",
				ver:"1.0",
				css:"./module/appintroduce/qqweb.app.appintroduce.css",
				js:"./module/appintroduce/qqweb.app.appintroduce.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_NOCHAT,
				width:620,
				height:500,
				windowMode:"multi",
				hasToolBar:0,
				resize:!1,
				hasMinButton:!1,
				hasMaxButton:!1,
				settingCenter:0
			},
			buddyAdder:{
				id:"buddyAdder",
				appName:"\u6dfb\u52a0\u597d\u53cb",
				appType:1,
				appLevel:"system",
				css:"./module/buddyadder/qqweb.app.buddyadder.css",
				js:"./module/buddyadder/qqweb.app.buddyadder.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_ALL,windowMode:"multi",
				windowType:"EqqWindow",
				hasToolBar:0,
				needApp:["eqq"],
				settingCenter:0
			},
			buddyFinder:{
				id:"buddyFinder",
				appName:"\u67e5\u627e\u597d\u53cb/\u7fa4",
				appDesc:"WebQQ\u4e3a\u4f60\u63d0\u4f9b\u7684\u67e5\u627eQQ\u7fa4\u670d\u52a1\uff0c\u652f\u6301\u901a\u8fc7\u7fa4\u53f7\u7801\uff0c\u5173\u952e\u5b57\u67e5\u627e\u60a8\u6240\u9700\u8981\u7684\u7fa4\u3002\u8be5\u670d\u52a1\u9700\u8981\u767b\u9646QQ\u624d\u80fd\u4f7f\u7528\u3002",
				appDesc:"Q+ Web\u4e3a\u4f60\u63d0\u4f9b\u7684\u67e5\u627eQQ\u7fa4\u670d\u52a1\uff0c\u652f\u6301\u901a\u8fc7\u7fa4\u53f7\u7801\uff0c\u5173\u952e\u5b57\u67e5\u627e\u60a8\u6240\u9700\u8981\u7684\u7fa4\u3002\u8be5\u670d\u52a1\u9700\u8981\u767b\u9646QQ\u624d\u80fd\u4f7f\u7528\u3002",
				appType:1,
				appLevel:"system",
				css:"./module/buddyfinder/qqweb.app.buddyfinder.css",
				js:"./module/buddyfinder/qqweb.app.buddyfinder.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_ALL,
				width:540,
				height:362,
				modeSwitch:!1,
				resize:!1,
				hasMinButton:!1,
				hasToolBar:0,
				hasMaxButton:!1,
				hasNextButton:!0,
				windowType:"EqqWindow",
				hasCancelButton:!0,
				needApp:["eqq"],
				settingCenter:0
			},
			screenLocker:{
				id:"screenLocker",
				appName:"\u9501\u5c4f",
				appType:1,
				appLevel:"system",
				css:"./module/screenlocker/qqweb.app.screenlocker.css",
				js:"./module/screenlocker/qqweb.app.screenlocker.js",
				windowMode:"none",
				hasToolBar:0,
				settingCenter:0
			},
			screenCapture:{
				id:"screenCapture",
				appName:"\u622a\u5c4f",
				appType:1,
				appLevel:"system",
				css:"./module/screencapture/qqweb.app.screencapture.css",
				js:"./module/screencapture/qqweb.app.screencapture.js",
				windowMode:"none",
				settingCenter:0
			},
			screenCapture2:{
				id:"screenCapture2",
				appName:"webtop\u622a\u5c4f",
				appType:1,
				appLevel:"system",
				css:"./module/screencapture2/style.css",
				js:"./module/screencapture2/main.js",
				windowMode:"none",
				settingCenter:0
			},
			settingCenter:{
				id:"settingCenter",
				appName:"\u7cfb\u7edf\u8bbe\u7f6e",
				appType:1,
				appLevel:"system",
				css:"./module/settingcenter/qqweb.app.settingcenter.css",
				js:"./module/settingcenter/qqweb.app.settingcenter.js",
				hasCloseButton:!0,
				hasMinButton:!1,
				hasMaxButton:!1,
				resize:!1,
				hasToolBar:0,
				settingCenter:0
			},
			explorer:{
				id:"explorer",
				appName:"\u8d44\u6e90\u7ba1\u7406\u5668",
				appType:1,
				appLevel:"system",
				css:"./module/explorer/style.css",
				js:"./module/explorer/main.js",
				hasCloseButton:!0,
				hasMinButton:!0,
				hasMaxButton:!0,
				resize:!0,
				hasToolBar:0,
				settingCenter:0,
				windowMode:"multi"
			},
			diskExplorer:{
				id:"diskExplorer",
				appName:"\u4e91\u5b58\u50a8",
				appType:1,
				appLevel:"system",
				css:"./module/diskexplorer/style.css",
				js:"./module/diskexplorer/main.js",
				hasCloseButton:!0,
				hasMinButton:!0,
				hasMaxButton:!0,
				resize:!0,
				hasToolBar:0,
				settingCenter:0,
				windowMode:"multi"
			},
			layoutSaver:{
				id:"layoutSaver",
				appName:"\u8bb0\u5fc6\u684c\u9762\u5e03\u5c40",
				appType:1,
				appLevel:"system",
				css:"./module/layoutsaver/qqweb.app.layoutsaver.css",
				js:"./module/layoutsaver/qqweb.app.layoutsaver.js",
				windowMode:"none",
				settingCenter:0
			},
			sceneChristmas:{
				id:"sceneChristmas",
				appName:"\u5723\u8bde\u5feb\u4e50",
				appType:1,
				appLevel:"system",
				css:"./scene/christmas/style.css",
				js:"./scene/christmas/main.js",
				settingCenter:0
			},
			gravity:{
				id:"gravity",
				appName:"\u83ca\u82b1",
				appType:1,
				appLevel:"system",
				css:"./scene/gravity/style.css",
				js:"./scene/gravity/main.js",
				settingCenter:0
			},
			urlSave:{
				id:"urlSave",
				appType:1,
				appName:"\u4e00\u952e\u53e6\u5b58\u4e3a\u5e94\u7528",
				appLevel:"system",
				appDesc:"\u5728\u8fd9\u91cc\uff0c\u4e00\u952e\u53e6\u5b58\u4e3a",
				ver:"1.0",
				css:"./module/urlsave/qqweb.app.urlsave.css",
				js:"./module/urlsave/qqweb.app.urlsave.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_NOCHAT,
				width:688,
				height:398,
				hasMinButton:!1,
				hasMaxButton:!1,
				resize:!1,
				hasOkButton:!0,
				hasCancelButton:!0,
				hasToolBar:0,
				settingCenter:0
			},
			activityGameCollection:{
				id:"activityGameCollection",
				appName:"WebGame\u5927\u96c6\u5408",
				appDesc:"WebGame\u5927\u96c6\u5408,\u7cbe\u9009WebGame,\u7545\u4eab\u5a31\u4e50",
				appType:1,
				appLevel:"system",
				css:"./activity/gamecollection/style.css",
				js:"./activity/gamecollection/main.js",
				hasCloseButton:!0,
				hasMinButton:!1,
				hasToolBar:0,
				width:740,
				height:530,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,settingCenter:0
			},
			activityChildsday:{
				id:"activityChildsday",
				appName:"\u513f\u7ae5\u8282\u5927\u96c6\u5408",
				appDesc:"\u513f\u7ae5\u8282\u5927\u96c6\u5408,\u7545\u4eab\u5a31\u4e50",
				appType:1,
				appLevel:"system",
				css:"./activity/childsday/style.css",
				js:"./activity/childsday/main.js",
				hasCloseButton:!0,
				hasMinButton:!1,
				hasToolBar:0,
				width:940,
				height:550,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,
				settingCenter:0
			},
			activity3366:{
				id:"activity3366",
				appName:"3366\u6d3b\u52a8",
				appDesc:"3366\u6d3b\u52a8",
				appType:1,
				appLevel:"system",
				css:"./activity/3366/style.css",
				js:"./activity/3366/main.js",
				hasCloseButton:!0,
				hasMinButton:!1,
				hasToolBar:0,
				width:940,
				height:550,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,
				settingCenter:0
			},
			restoreSetting:{
				id:"restoreSetting",
				appName:"\u7cfb\u7edf\u8fd8\u539f",
				appType:1,
				appLevel:"system",
				css:"./module/restoresetting/style.css",
				js:"./module/restoresetting/main.js",
				hasMinButton:!1,
				hasMaxButton:!1,
				hasOkButton:!0,
				hasCancelButton:!0,
				resize:!1,
				hasToolBar:0,
				settingCenter:0
			},
			mapLocation:{
				id:"mapLocation",
				appName:"html5\u5730\u56fe\u5b9a\u4f4d",
				appType:2,
				x:1,
				y:420,
				appDesc:"html5\u5730\u56fe\u5b9a\u4f4d",
				appLevel:"system",
				appUrl:qqweb.CONST.MAIN_URL+"module/maplocation/maplocation.html",
				width:224,
				height:185,
				windowType:"widget",
				hasToolBar:0,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,
				settingCenter:0
			},
			selectBuddy:{
				id:"selectBuddy",
				appName:"\u9009\u62e9\u8054\u7cfb\u4eba",
				appDesc:"\u9009\u62e9\u8054\u7cfb\u4eba",
				appType:1,
				appLevel:"system",
				css:"./module/selectbuddy/style.css",
				js:"./module/selectbuddy/main.js",
				loginLevel:alloy.CONST.LOGIN_LEVEL_NOCHAT,
				windowMode:"multi",
				settingCenter:0
			},
			99999:{
				id:"99999",
				appName:"\u89c6\u9891\u804a\u5929",
				appType:2,
				width:384,
				height:320,
				hasMinButton:!1,
				hasMaxButton:!1,
				appLevel:"system",
				appUrl:"http://vcall.hehehi.com",
				hasToolBar:0,
				powerLevel:3
			},
			cloud:{
				id:"cloud",
				appName:"\u4e91\u6735",
				appType:1,
				appLevel:"system",
				css:"./scene/cloud/style.css",
				js:"./scene/cloud/main.js",
				settingCenter:0
			},
			activitySaturday:{
				id:"activitySaturday",
				appName:"\u793c\u62dc\u516d\u56e2\u961f\u4e13\u8bbf",
				appDesc:"\u793c\u62dc\u516d\u56e2\u961f\u4e13\u8bbf\u3002",
				appType:1,
				appLevel:"system",
				css:"./activity/saturday/style.css",
				js:"./activity/saturday/main.js",
				hasCloseButton:!0,
				hasMinButton:!1,
				hasMaxButton:!0,
				resize:!0,
				hasToolBar:0,
				width:900,
				height:550,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,
				settingCenter:0
			},
			activityXindongfang:{
				id:"activityXindongfang",
				appName:"\u6dfb\u52a0\u65b0\u4e1c\u65b9\u5e94\u7528\uff0c\u8d62\u53d6\u8d2d\u8bfe\u4ee3\u91d1\u5238",
				appDesc:"\u6dfb\u52a0\u65b0\u4e1c\u65b9\u5e94\u7528\uff0c\u8d62\u53d6\u8d2d\u8bfe\u4ee3\u91d1\u5238",
				appType:1,
				appLevel:"system",
				css:"./activity/xindongfang/style.css",
				js:"./activity/xindongfang/main.js",
				hasCloseButton:!0,
				hasMinButton:!1,
				hasMaxButton:!0,
				hasToolBar:0,
				width:780,
				height:530,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,settingCenter:0
			},
			appGrant:{
				id:"appGrant",
				appName:"\u5e94\u7528\u6388\u6743",
				appType:1,
				appLevel:"system",
				css:"./module/appgrant/qqweb.app.grant.css",
				js:"./module/appgrant/qqweb.app.grant.js",
				windowMode:"none",
				hasToolBar:0,
				settingCenter:0
			},
			imgViewer:{
				id:"imgViewer",
				appName:"Q+ Web\u56fe\u7247\u64ad\u653e\u5668",
				appDesc:"Q+ Web\u56fe\u7247\u64ad\u653e\u5668",
				appType:1,css:"./module/imgviewer/qqweb.img.viewer.css",
				js:"./module/imgviewer/qqweb.img.viewer.js",
				hasToolBar:0,
				width:760,
				height:502,
				minWidth:390,
				minHeight:155,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,
				quickPanel:1,
				settingCenter:0
			},
			docViewer:{
				id:"docViewer",
				appName:"Q+ Web\u6587\u6863\u6d4f\u89c8\u5668",
				appDesc:"Q+ Web\u6587\u6863\u6d4f\u89c8\u5668",
				appType:2,
				appUrl:qqweb.CONST.MAIN_URL+"module/docviewer/docviewer.html",
				hasToolBar:0,
				width:1E3,
				height:540,
				minWidth:300,
				minHeight:320,
				exinfo:{powerLevel:20},
				powerLevel:20,
				quickPanel:1,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,
				settingCenter:0
			},
			audioPlayer:{
				id:"audioPlayer",
				appName:"Q+ Web\u97f3\u9891\u64ad\u653e\u5668",
				appDesc:"Q+ Web\u97f3\u9891\u64ad\u653e\u5668",
				appType:2,
				appUrl:qqweb.CONST.MAIN_URL+"module/audioplayer/audioplayer.html?"+qqweb.CONST.UPDATE_TIME_STAMP,
				windowType:"widget",
				hasToolBar:0,
				hasMinButton:!0,
				hasMaxButton:!1,
				width:228,
				height:84,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NONE,
				quickPanel:1,
				quickPanelIcon:"./style/images/audioplayer.gif",
				settingCenter:0,
				powerLevel:200,
				exinfo:{powerLevel:200}
			},
			messageCenter:{
				id:"messageCenter",
				appName:"\u6d88\u606f\u4e2d\u5fc3",
				appDesc:"Q+ Web \u6d88\u606f\u4e2d\u5fc3",
				appType:2,
				appLevel:"system",
				appUrl:qqweb.CONST.MAIN_URL+"module/messagecenter/messagecenter.html?"+qqweb.CONST.UPDATE_TIME_STAMP,
				hasCloseButton:!0,
				hasMinButton:!0,
				hasMaxButton:!1,
				modeSwitch:!0,
				resize:!1,
				width:640,
				height:482,
				hasToolBar:0,
				loginLevel:alloy.CONST.LOGIN_LEVEL_NOCHAT,
				settingCenter:0,
				quickPanel:1
			}
		};
		this.getAppConfigList=function(){return this.appConfigList};
		this.getAllConfig=function(b){return v(b,this.appConfigList)||v(b,this.systemConfigList)};
		this.getAppConfig=function(c){if((c=v(c,this.appConfigList))&&(b.isUndefined(c.id)||b.isUndefined(c.appName)))c=null,alloy.util.report2m(151399);return c};
		this.getSystemConfig=function(b){return v(b,this.systemConfigList)};
		this.isAppConfigLoad=function(){return j};
		var v=function(b,a){
			if(b&&b.call){
				var c=[],d;
				for(d in a){
					var e=a[d];
					b(e)&&c.push(e)
				}
				return c
			}else 
				return a[b]
		};
		this.clearConfig=function(){this.appConfigList={}};
		this.addAppConfigList=function(e){
			var a=e.result.resultData;
			b.profile("AddAppConfigList");
			for(var f in a)
				a[f]?a[f].isDel?(alloy.config.setDeleteAppList(a[f].id),delete a[f]):(a[f].title=a[f].appName,a[f].type=a[f].appType,b.extend(a[f],a[f].exinfo)):delete a[f];
			b.extend(this.appConfigList,a);
			b.profile("AddAppConfigListEnd");
			c.notifyObservers(d,"AddAppConfigList",e)
		};
		this.addAppConfig=function(e){
			b.profile("addAppConfig");
			this.appConfigList[e.id]=b.extend(e,e.exinfo);
			var a={
				appid:e.id,
				value:1,
				type:0
			};
			e.id<1E5&&x(a);
			c.notifyObservers(d,"AddAppConfig",e);
			if((a=alloy.system.getApp("appMarket"))&&a._iframe)
				a._iframe.contentWindow.appMarket.onAddAppConfig(e)
		};
		this.addAppConfigTemp=function(c){
			b.profile("addAppConfig Temp");
			this.appConfigList[c.id]=b.extend(c,c.exinfo)
		};
		this.updateAppConfig=function(e){
			b.profile("updateAppConfig");
			this.appConfigList[e.id]=e;
			c.notifyObservers(d,"UpdateAppConfig",e)
		};
		this.removeAppConfig=function(e){
			b.profile("removeAppConfig");
			delete this.appConfigList[e.id];
			var a={appid:e.id,value:-1,type:0};
			e.id<1E5&&x(a);
			c.notifyObservers(d,"RemoveAppConfig",e);
			if((a=alloy.system.getApp("appMarket"))&&a._iframe)
				a._iframe.contentWindow.appMarket.onRemoveAppConfig(e)
		};
		this.setNewSystemAppCount=function(b){q=b};
		this.setNewAllAppCount=function(b){u=b};
		this.getNewSystemAppCount=function(){return q};
		this.getNewAllAppCount=function(){return u};
		this.isQplusApp=function(b){
			if(isNaN(b))
				return!1;
			b=d.getAppConfig(b);
			return!b?!1:(b=b.gaid)&&b>=2E8&&b<3E8?!0:!1
		};
		var x=function(e){
			alloy.config.isSetupAppListLoaded()&&alloy.rpcService.cgiSend(
				alloy.CONST.JAVA_CGI_URL+"cgi/qqweb/market/updateapphot.do",
				{
					context:d,
					method:"POST",
					data:{
						appattrib:b.json.stringify(e),
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					arguments:e,
					onSuccess:function(a){
						a.retcode!==0&&b.out("\u5e94\u7528\u6b21\u6570\u6dfb\u52a0\u5931\u8d25"+a.errmsg)
					},
					onError:function(a){
						b.out("\u5e94\u7528\u6b21\u6570\u6dfb\u52a0\u5931\u8d25");
						c.notifyObservers(d,"SetAppCountError",a)
					}
				}
			)
		},
		m=function(h,a){
			alloy.rpcService.cgiSend(
				alloy.CONST.JAVA_CGI_URL+a,
				{
					context:d,
					method:"POST",
					arguments:h.appid,
					timeout:2E4,
					data:{
						appattrib:b.json.stringify(h),
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					onSuccess:function(f){
						if(f.retcode===0)
							if(typeof progress=="function"&&progress("get_appinfo end"),alloy.util.report2qqweb("config|appconfig|success"),g)
								alloy.util.report2h("get_def_appinfo","end"),
								this.addAppConfigList(f),
								e.setItem("UPDATE_TIME_STAMP",alloy.CONST.UPDATE_TIME_STAMP),
								e.setItem("defaultAppConfig",b.json.stringify(d.getAppConfigList())),
								c.notifyObservers(d,"GetDefaultAppConfigComplete",this.getAppConfigList()),
								b.profile("\u9ed8\u8ba4app config\u5b8c\u6210"),
								alloy.util.report2h("def_appinfo","end");
							else{
								alloy.util.report2h("get_appinfo","end");
								c.notifyObservers(d,"GetAppConfigAsPartSuccess",f.result);
								l++;
								var n=alloy.config.getSetupAppList(),
									q=l*100,
									o=(l+1)*100;
								this.addAppConfigList(f);
								q<n.length?(
									n=n.slice(q,o),
									m(
										{
											appid:n,
											loadMethod:3,
											val:["appName","appType","appUrl","iconUrl","id","category","exinfo","al"]
										},
										"keycgi/qqweb/market/getappinfonew.do"
									)
								):(
									j=!0,
									b.isUndefined(f.userflag)
									||
									alloy.portal.setIsNewUser(f.userflag==0?!0:!1),
									c.notifyObservers(d,"GetAppConfigComplete",this.getAppConfigList()),
									alloy.portal.speedTest.sRTS(5,"end",new Date,!0),
									b.profile("\u81ea\u5b9a\u4e49app config\u5b8c\u6210")
								)
							}
						else 
							f.retcode==1E5?(
								timeoutConfirm("\u767b\u5f55\u4fe1\u606f\u8d85\u65f6,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f"),
								alloy.util.report2qqweb("config|appconfig|logintimeout"),
								p<1?(++p,m(h,a)):(
									timeoutConfirm("\u767b\u5f55\u4fe1\u606f\u8d85\u65f6,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f"),
									alloy.util.report2qqweb("config|appconfig|logintimeout")
								)
							):(
								timeoutConfirm("\u83b7\u53d6\u5e94\u7528\u4fe1\u606f\u51fa\u9519,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f"),
								alloy.util.report2qqweb("config|appconfig|reterror"),
								c.notifyObservers(d,"GetAppConfigError",f.resutlt),
								b.error("get app config \u8fd4\u56de\u7ed3\u679c\u4e0d\u6b63\u786e. data: "+f,"AppConfig"),
								p<1?(++p,m(h,a)):(
									timeoutConfirm("\u83b7\u53d6\u5e94\u7528\u4fe1\u606f\u51fa\u9519,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f"),
									alloy.util.report2qqweb("config|appconfig|reterror"),
									c.notifyObservers(d,"GetAppConfigError",f.resutlt),
									b.error("get app config \u8fd4\u56de\u7ed3\u679c\u4e0d\u6b63\u786e. data: "+f,"AppConfig")
								)
							);
						qqweb.util.report2h("appinfo","end",["ok"][f.retcode]||f.retcode)
					},
					onError:function(e){
						b.profile("GetAppConfigError");
						qqweb.util.report2h(g?"def_appinfo":"appinfo","end","error");
						c.notifyObservers(d,"GetAppConfigError",e.resutlt);
						timeoutConfirm("\u83b7\u53d6\u5e94\u7528\u4fe1\u606f\u51fa\u9519,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f");
						alloy.util.report2qqweb("config|appconfig|error");
						p<1?(++p,m(h,a)):(
							qqweb.util.report2h(g?"def_appinfo":"appinfo","end","error"),
							c.notifyObservers(d,"GetAppConfigError",e.resutlt),
							timeoutConfirm("\u83b7\u53d6\u5e94\u7528\u4fe1\u606f\u51fa\u9519,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f"),
							alloy.util.report2qqweb("config|appconfig|error")
						)
					},
					onTimeout:function(b){
						timeoutConfirm("\u83b7\u53d6\u5e94\u7528\u4fe1\u606f\u8d85\u65f6,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f");
						alloy.util.report2qqweb("config|appconfig|timeout");
						c.notifyObservers(d,"GetAppConfigError",b.resutlt);
						qqweb.util.report2h(g?"def_appinfo":"appinfo","end","timeout");
						p<1?(++p,m(h,a)):(
							timeoutConfirm("\u83b7\u53d6\u5e94\u7528\u4fe1\u606f\u8d85\u65f6,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f"),
							alloy.util.report2qqweb("config|appconfig|timeout"),
							c.notifyObservers(d,"GetAppConfigError",b.resutlt),
							qqweb.util.report2h(g?"def_appinfo":"appinfo","end","timeout")
						)
					}
				}
			)
		},
		o={
			onAlloyReady:function(){
				b.profile("UACReady\uff1a"+alloy.config.isSetupAppListLoaded());
				if(alloy.config.isSetupAppListLoaded())
					if(j)
						c.notifyObservers(d,"GetAppConfigComplete");
					else{
						c.notifyObservers(d,"ClearDefaultApp");
						var h;
						h=alloy.config.getSetupAppList();
						d.clearConfig();
						g=!1;
						l=0;
						h=h.slice(0,100);
						b.profile("\u62c9\u53d6\u81ea\u5b9a\u4e49app config");
						alloy.util.report2h("appinfo","start");
						typeof progress=="function"&&progress("get_appinfo start");
						m({appid:h,loadMethod:3,val:["appName","appType","appUrl","iconUrl","id","category","exinfo","al","gaid"]},"keycgi/qqweb/market/getappinfonew.do")
					}
				else{
					g=!0;
					b.profile("\u62c9\u53d6\u9ed8\u8ba4app config",b.console.TYPE.WARNING);
					alloy.util.report2h("def_appinfo","start");
					typeof progress=="function"&&progress("get_def_appinfo start");
					if(e.getItem("UPDATE_TIME_STAMP")==alloy.CONST.UPDATE_TIME_STAMP&&(h=e.getItem("defaultAppConfig"))){
						d.appConfigList=b.json.parse(h);
						c.notifyObservers(d,"GetDefaultAppConfigComplete",d.getAppConfigList());
						b.profile("\u9ed8\u8ba4app config\u5b8c\u6210");
						alloy.util.report2h("def_appinfo","end");
						return
					}
					m(
						{
							appid:alloy.config.getDefaultSetupAppList(),
							loadMethod:3,
							val:[
								"appName",
								"appType",
								"appUrl",
								"iconUrl",
								"id",
								"category",
								"exinfo",
								"al",
								"gaid"
							]
						},
						"/keycgi/qqweb/market/getdefaultappinfonew.php"
					)
				}
			},
			onReset:function(){j=!1}
		};
		c.addObserver(alloy.portal,"reset",o.onReset);
		c.addObserver(alloy.portal,"AlloyReady",o.onAlloyReady)
	}
);