Jx().$package("alloy.layout.themeManager",function(b){
		var d=this,
			c=b.dom,
			e=b.event,
			g,
			j,
			l,
			q,
			u={id:"theme_blue_glow"},
			p=null,
			v=0;
		window.webTop&&(u={id:"theme_blue_glow"});
		var x;
		this.themeConfig={
			theme_blue:{
				id:"theme_blue",
				name:"\u68a6\u5e7b\u5149\u5f71",
				skin:"blue",
				wallpaper:{
					url:"blue.jpg?t=20111011001",
					mode:"centerRepeat"
				}
			},
			theme_pinky_night:{
				id:"theme_pinky_night",
				name:"\u7c89\u7ea2\u4e4b\u591c",
				skin:"pink",
				wallpaper:{
					url:"pinky_night.jpg?t=20111011001",
					mode:"centerRepeat"
				}
			},
			theme_green:{
				id:"theme_green",
				name:"\u9752\u9752\u4e16\u754c",
				skin:"light_green",
				wallpaper:{
					url:"green.jpg",
					mode:"centerRepeat"
				}
			},
			theme_wood1:{
				id:"theme_wood1",
				name:"\u6e29\u99a8\u6728\u7eb9",
				skin:"dark_brown",
				wallpaper:{
					url:"wood1.jpg",
					mode:"centerRepeat"
				}
			},
			theme_wood2:{
				id:"theme_wood2",
				name:"\u9ed1\u8272\u6728\u7eb9",
				skin:"black",
				wallpaper:{
					url:"wood2.jpg",
					mode:"centerRepeat"
				}
			},
			theme_universe:{
				id:"theme_universe",
				name:"\u795e\u79d8\u661f\u9645",
				skin:"dark_blue",
				wallpaper:{
					url:"universe.jpg?t=20111011001",
					mode:"centerRepeat"
				}
			},
			theme_metal:{
				id:"theme_metal",
				name:"\u9177\u70ab\u91d1\u5c5e",
				skin:"grey",
				wallpaper:{
					url:"metal.jpg?t=20111011001",
					mode:"centerRepeat"
				}
			},
			theme_pinky_light:{
				id:"theme_pinky_light",
				name:"\u5e7b\u5f69\u8367\u5149",
				skin:"light_violet",
				wallpaper:{
					url:"pinky_light.jpg?t=20111011001",
					mode:"fill"
				}
			},
			theme_pinky_flower:{
				id:"theme_pinky_flower",
				name:"\u7eda\u70c2\u7e41\u82b1",
				skin:"dark_voilet",
				wallpaper:{
					url:"pinky_flower.jpg?t=20111011001",
					mode:"fill"
				}
			},
			theme_christmas:{
				id:"theme_christmas",
				name:"\u5723\u8bde\u5feb\u4e50",
				skin:"light_blue",
				wallpaper:{
					url:"christmas.jpg?t=20111011001",
					mode:"fill"
				},
				scene:"sceneChristmas"
			},
			theme_2011:{
				id:"theme_2011",
				name:"\u6b22\u5e86\u5143\u65e6",
				skin:"black",
				wallpaper:{
					url:"2011.jpg",
					mode:"fill"
				}
			},
			theme_blue1:{
				id:"theme_blue1",
				name:"\u5e7b\u5f69\u84dd\u5929",
				skin:"dark_blue",
				wallpaper:{
					url:"blue1.jpg?t=20111011001",
					mode:"fill"
				}
			},
			theme_spring_festival:{
				id:"theme_spring_festival",
				name:"\u559c\u8fce\u65b0\u6625",
				skin:"grey",
				wallpaper:{
					url:"spring_festival.jpg?t=20111011001",
					mode:"centerRepeat"
				}
			},
			theme_valentinesDay:{
				id:"theme_valentinesDay",
				name:"\u751c\u871c\u60c5\u4eba\u8282",
				skin:"valentinesDay",
				wallpaper:{
					url:"valentinesDay.jpg?t=20111011001",
					mode:"fill"
				}
			},
			theme_cloud:{
				id:"theme_cloud",
				name:"\u6674\u7a7a\u884c\u4e91",
				skin:"blue",
				wallpaper:{
					url:"cloud.jpg?t=20111011001",
					mode:"centerRepeat"
				},
				scene:"cloud"
			},
			theme_gravity:{
				id:"theme_gravity",
				name:"\u84b2\u516c\u82f1",
				skin:"blue",
				wallpaper:{
					url:"cloud.jpg?t=20111011001",
					mode:"centerRepeat"
				},
				scene:"gravity"
			},
			theme_blue_glow:{
				id:"theme_blue_glow",
				name:"\u6df1\u6d77\u4ef0\u671b",
				skin:"grey",
				wallpaper:{
					url:"blue_glow.jpg",
					mode:"zoom"
				}
			},
			theme_green_glow:{
				id:"theme_green_glow",
				name:"\u6668\u5149\u5fae\u66e6",
				skin:"grey",
				wallpaper:{
					url:"green_glow.jpg",
					mode:"zoom"
				}
			},
			theme_orange_glow:{
				id:"theme_orange_glow",
				name:"\u68a6\u9192\u65f6\u5206",
				skin:"grey",
				wallpaper:{
					url:"orange_glow.jpg",
					mode:"zoom"
				}
			},
			theme_7_7:{
				id:"theme_7_7",
				name:"\u4e03\u5915",
				skin:"7_7",
				wallpaper:{
					url:"7_7.jpg",
					mode:"fill"
				}
			},
			theme_teachersDay:{
				id:"theme_teachersDay",
				name:"\u6559\u5e08\u8282",
				skin:"teachersDay",
				wallpaper:{
					url:"teachersDay.jpg",
					mode:"zoom"
				}
			},
			theme_midAutumn:{
				id:"theme_midAutumn",
				name:"\u4e2d\u79cb\u8282",
				skin:"pink",
				wallpaper:{
					url:"midAutumn.jpg",
					mode:"fill"
				}
			},
			theme_lookUpSky:{
				id:"theme_lookUpSky",
				name:"\u4ef0\u671b\u82cd\u7a79",
				skin:"blue",
				wallpaper:{
					url:"lookUpSky.jpg",
					mode:"fill"
				}
			},
			theme_grass:{
				id:"theme_grass",
				name:"\u832b\u832b\u91ce\u8349",
				skin:"grey",
				wallpaper:{
					url:"grass.jpg",
					mode:"fill"
				}
			},
			theme_childhood:{
				id:"theme_childhood",
				name:"\u7ae5\u5e74\u8bb0\u5fc6",
				skin:"pink",
				wallpaper:{
					url:"childhood.jpg",
					mode:"fill"
				}
			},
			theme_skyBlue:{
				id:"theme_skyBlue",
				name:"\u7a7a\u7075\u84dd\u8c03",
				skin:"blue",
				wallpaper:{
					url:"skyBlue.jpg",
					mode:"fill"
				}
			},
			theme_dandelionDream:{
				id:"theme_dandelionDream",
				name:"\u84b2\u82f1\u4e4b\u68a6",
				skin:"blue",
				wallpaper:{
					url:"dandelionDream.jpg",
					mode:"fill"
				}
			},
			theme_paintingTime:{
				id:"theme_paintingTime",
				name:"\u6c34\u58a8\u5e74\u534e",
				skin:"dark_brown",
				wallpaper:{
					url:"paintingTime.jpg",
					mode:"fill"
				}
			},
			theme_dreamSky:{
				id:"theme_dreamSky",
				name:"\u68a6\u7fd4\u5929\u9645",
				skin:"blue",
				wallpaper:{
					url:"dreamSky.jpg",
					mode:"fill"
				}
			}
		};
		var m=[];
		(function(){
			var a,b=0;
			for(a in d.themeConfig)
				d.themeConfig.hasOwnProperty(a)&&(m[b++]=d.themeConfig[a])
		})();
		this.themeArray=m;
		this.getThemeArray=function(a){
			var c=[],e;
			for(e=0;e<a.length;e++)
				b.browser.mobileSafari&&a[e]=="theme_gravity"||c.push(d.themeConfig[a[e]]);
			return c
		};
		var o={
			skinRoot:"",
			timeStamp:20111011001,
			window:{
				titleColor:"#6d6d6d",
				titleHeight:"25px",
				textColor:"#666666",
				titleFontWeight:"bold",
				bodyAreaTop:"0",
				actionButtonWidth:"21px",
				actionButtonHeight:"19px",
				bodyColor:"#fff",
				ie6WindowCenterBackground:"#C2D2C8",
				ipadContainerBackColor:"rgba(168, 218, 127, .8)"
			},
			currentWindow:{
				titleColor:"#393836",
				textColor:"#333333",
				ipadContainerBackColor:"rgba(168, 218, 127, 1)",
				windowCenterBackground:"#A8DA7F",
				ie6WindowCenterBackground:"#A8DA7F"
			},
			appbar:{
				aColor:"white"
			},
			panel:{
				ie6Background:"#fff"
			},
			indicator:{
				bgHeight:"40px",
				ie6BgHeight:"28px",
				wrapperTop:"0",
				wrapperPosition:"static",
				ipadSystemBtn:".mobileSafari #navbar{width:222px;} .mobileSafari #navbar .system_button{display:none;visibility:visible;}"
			}
		},
		h=this.skinConfig={
			blue:{
				id:0,
				key:"blue",
				name:"\u6de1\u84dd",
				timeStamp:20111011001,
				window:{
					bodyColor:"#C4DCEA",
					ipadContainerBackColor:"rgba(182,234,253,.8)",
					ie6WindowCenterBackground:"#C4DEED"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(182,234,253,1)",
					ie6WindowCenterBackground:"#B6EAFD"
				}
			},
			black:{
				id:1,
				key:"black",
				name:"\u9ed1\u8272",
				timeStamp:20111011001,
				window:{
					bodyColor:"#E9E9E9",
					ipadContainerBackColor:"rgba(232,232,232,.8)",
					ie6WindowCenterBackground:"#C4C4C4"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(232,232,232,1)",
					ie6WindowCenterBackground:"#e8e8e8"
				}
			},
			light_green:{
				id:2,
				key:"light_green",
				name:"\u5ae9\u7eff",
				timeStamp:20111011001,
				window:{
					bodyColor:"#AFDD8B",
					ipadContainerBackColor:"rgba(168,218,127,.8)",
					ie6WindowCenterBackground:"#C2D2C8"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(168,218,127,1)",
					ie6WindowCenterBackground:"#A8DA7F"
				}
			},
			pink:{
				id:3,
				key:"pink",
				name:"\u6c34\u7c89",
				timeStamp:20111011001,
				window:{
					bodyColor:"#EFDEE5",
					ipadContainerBackColor:"rgba(255,225,229,.8)",
					ie6WindowCenterBackground:"#CCCCCC"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(255,225,229,1)",
					ie6WindowCenterBackground:"#FFE1E5"
				}
			},
			light_violet:{
				id:4,
				key:"light_violet",
				name:"\u6d45\u7d2b",
				timeStamp:20111011001,
				window:{
					bodyColor:"#EFDEE5",
					ipadContainerBackColor:"rgba(255,225,229,.8)",
					ie6WindowCenterBackground:"#CCCCCC"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(255,225,229,1)",
					ie6WindowCenterBackground:"#FFE1E5"
				}
			},
			dark_voilet:{
				id:5,
				key:"dark_voilet",
				name:"\u7d20\u7d2b",
				timeStamp:20111011001,
				window:{
					bodyColor:"#EFDEE5",
					ipadContainerBackColor:"rgba(255,225,229,.8)",
					ie6WindowCenterBackground:"#CCCCCC"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(255,225,229,1)",
					ie6WindowCenterBackground:"#FFE1E5"
				}
			},
			grey:{
				id:6,
				key:"grey",
				name:"\u94f6\u7070",
				timeStamp:20111011001,
				window:{
					bodyColor:"#E9E9E9",
					ipadContainerBackColor:"rgba(232,232,232,.8)",
					ie6WindowCenterBackground:"#C4C4C4"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(232,232,232,1)",
					ie6WindowCenterBackground:"#e8e8e8"
				}
			},
			dark_brown:{
				id:7,
				key:"dark_brown",
				name:"\u6d45\u68d5",
				timeStamp:20111011001,
				window:{
					bodyColor:"#E2D3BB",
					ipadContainerBackColor:"rgba(234,222,197,.8)",
					ie6WindowCenterBackground:"#C4C4C4"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(234,222,197,1)",
					ie6WindowCenterBackground:"#EADEC5"
				}
			},
			dark_blue:{
				id:8,
				key:"dark_blue",
				name:"\u6df1\u84dd",
				timeStamp:20111011001,
				window:{
					bodyColor:"#E9E9E9",
					ipadContainerBackColor:"rgba(232,232,232,.8)",
					ie6WindowCenterBackground:"#C4C4C4"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(232,232,232,1)",
					ie6WindowCenterBackground:"#e8e8e8"
				}
			},
			light_blue:{
				id:9,
				key:"light_blue",
				name:"\u6d45\u84dd",
				timeStamp:20111011001,
				window:{
					bodyColor:"#C4DCEA",
					ipadContainerBackColor:"rgba(232,232,232,.8)",
					ie6WindowCenterBackground:"#C4DEED"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(232,232,232,1)",
					ie6WindowCenterBackground:"#B6EAFD"
				}
			},
			valentinesDay:{
				id:10,
				key:"valentinesDay",
					
				name:"\u6d45\u84dd",
					
				timeStamp:20111011001,
					
				window:{
					bodyColor:"#E9E9E9",
					ipadContainerBackColor:"rgba(232,232,232,.8)",
					ie6WindowCenterBackground:"#C4C4C4"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(232,232,232,1)",
					ie6WindowCenterBackground:"#e8e8e8"
				}
			},
			red:{
				id:11,
				key:"red",
				name:"\u4eae\u7ea2",
				timeStamp:20111011001,
				window:{
					bodyColor:"#F1B7B7",
					ipadContainerBackColor:"rgba(245,194,194,.8)",
					ie6WindowCenterBackground:"#F7CECE"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(245,194,194,1)",
					ie6WindowCenterBackground:"#F5C2C2"
				}
			},
			cyan:{
				id:12,
				key:"cyan",
				name:"\u78a7\u9752",
				timeStamp:20111011001,
				window:{
					bodyColor:"#BAE3D7",
					ipadContainerBackColor:"rgba(194,245,226,.8)",
					ie6WindowCenterBackground:"#CEF7E8"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(194,245,226,1)",
					ie6WindowCenterBackground:"#C2F5E2"
				}
			},
			purple:{
				id:13,
				key:"purple",
				name:"\u7d20\u7d2b",
				timeStamp:20111011001,
				window:{
					bodyColor:"#CAB7DE",
					ipadContainerBackColor:"rgba(224,194,245,.8)",
					ie6WindowCenterBackground:"#E6CEF7"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(224,194,245,1)",
					ie6WindowCenterBackground:"#E0C2F5"
				}
			},
			"7_7":{
				id:14,
				key:"7_7",
				name:"\u6c34\u7c89",
				timeStamp:20111011001,
				window:{
					bodyColor:"#EFDEE5",
					ipadContainerBackColor:"rgba(255,225,229,.8)",
					ie6WindowCenterBackground:"#CCCCCC"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(255,225,229,1)",
					ie6WindowCenterBackground:"#FFE1E5"
				}
			},
			teachersDay:{
				id:15,
				key:"teachersDay",
				name:"\u6de1\u84dd",
				timeStamp:20111011001,
				window:{
					ipadContainerBackColor:"rgba(182,234,253,.8)",
					ie6WindowCenterBackground:"#C4DEED"
				},
				currentWindow:{
					ipadContainerBackColor:"rgba(182,234,253,1)",
					ie6WindowCenterBackground:"#B6EAFD"
				}
			}
		};
		this.getSkinArray=function(a){
			var b=[],c;
			for(c=0;c<a.length;c++)
				b[c]=h[a[c]];
			return b
		};
		var a={},
			f={
				repeat:{
					isHackNeeded:!1,
					hackType:""
				},
				center:{
					isHackNeeded:!1,
					hackType:""
				},
				centerRepeat:{
					isHackNeeded:!1,
					hackType:""
				},
				zoom:{
					isHackNeeded:!0,
					hackType:"img"
				},
				adapt:{
					isHackNeeded:!0,
					hackType:"img"
				},
				fill:{
					isHackNeeded:!0,
					hackType:"img"
				},
				iframe:{
					isHackNeeded:!0,
					hackType:"iframe"
				}
			},
			n=function(){
				d.applyTheme(u?u.id:d.themeArray[Math.floor(Math.random()*100%d.themeArray.length)].id,!0)
			},
			s=function(a,b){
				var b=b||function(){},
					c=[],
					d=a.length;
				if(a.length)
					for(var e=function(){--d<1&&(b(c),c=null)},f=function(){this.onerror=this.onload=null;e()},g=function(){this.onerror=this.onload=null;e()};a.length>0;){
						var h=new Image;
						c.push(h);
						h.onload=f;
						h.onerror=g;
						h.src=a.shift()
					}
				else 
					b(c)
			},
			w=new b.Class({
					init:function(){
						this._iframeWallpaperContainter=this._zoomWallpaperContainer=null;
						this._mode="repeat";
						var a=this;
						this._onWindowResize=function(){a.setWallpaperSize.apply(a)}
					},
					getMode:function(){return this._mode},
					isHackLayerNeeded:function(){return!0},
					isHackLayerNeed2Change:function(){return f[this._mode].hackType!=f[this._nMode].hackType},
					isModeHackNeeded:function(a){return f[a].isHackNeeded},
					initHackLayer:function(){
						if(this.isHackLayerNeeded()&&(!this.isModeHackNeeded(this._mode)||this.isHackLayerNeed2Change()))
							this.onInitHackLayer(f[this._nMode].hackType)
					},
					onInitHackLayer:function(a){
						(this._zoomWallpaperContainer=c.id("zoomWallpaperGrid"))&&document.body.removeChild(this._zoomWallpaperContainer);
						switch(a){
							case "img":
								this._zoomWallpaperContainer=c.node(
									"div",
									{
										id:"zoomWallpaperGrid",
										"class":"zoomWallpaperGrid",
										style:"position:absolute;z-index:-10;left:0;top:0;overflow:hidden;"
									}
								);
								this._zoomWallpaperContext=c.node(
									"img",
									{
										id:"zoomWallpaper",
										"class":"zoomWallpaper",
										style:"position:absolute;"
									}
								);
								this._zoomWallpaperContainer.appendChild(this._zoomWallpaperContext);
								document.body.appendChild(this._zoomWallpaperContainer);
								e.on(window,"resize",this._onWindowResize);
								break;
							case "iframe":
								this._zoomWallpaperContainer=c.node(
									"div",
									{
										id:"zoomWallpaperGrid",
										"class":"zoomWallpaperGrid",
										style:"position:absolute;left:0;top:0;overflow:hidden;width:100%;height:100%;z-index:-1;"
									}
								),
								this._zoomWallpaperContext=c.node("div"),
								this._zoomWallpaperContext.innerHTML='<iframe id ="iframeWallpaper" frameborder="no" border="0" class ="iframeWallpaper" style ="position:absolute;left:0;top:0;overflow:hidden;width:100%;height:100%;"></iframe>',
								this._zoomWallpaperContainer.appendChild(this._zoomWallpaperContext),
								document.body.appendChild(this._zoomWallpaperContainer)
						}
					},
					removeHackLayout:function(){
						if(this.isHackLayerNeeded()&&this.isModeHackNeeded(this._mode)){
							if(this._zoomWallpaperContainer&&(c.setStyle(this._zoomWallpaperContainer,"display","none"),this._mode=="iframe"))
								c.id("iframeWallpaper").src="domain.html";
							e.off(window,"resize",this._onWindowResize)
						}else 
							this.isModeHackNeeded(this._mode)&&c.removeClass(document.body,"wallpaperCss3"+this._mode)
					},
					getCurrentWallpaper:function(){return this._wallpaper.src},
					getCurrentMode:function(){return this._wallpaper.mode},
					applyWallpaper:function(a,b){
						this._wallpaper={src:a,mode:b};
						this._nMode=b;
						b=="iframe"?this.applyIframeWallpaper(a):this.applyImageWallpaper(a,b)
					},
					applyImageWallpaper:function(a){s([a],b.bind(this.onWallpaperLoaded,this))},
					applyIframeWallpaper:function(a){
						this.initHackLayer();
						this._mode=this._nMode;
						if(this._zoomWallpaperContext)
							c.id("iframeWallpaper").src=a
					},
					applyBackColor:function(a){c.setStyle(document.body,"backbroundColor",a)},
					onWallpaperLoaded:function(a){
						this._wallpaper.height=a[0].height;
						this._wallpaper.width=a[0].width;
						a="url("+this._wallpaper.src+")";
						this._nMode=this._nMode||u&&u.mode||"repeat";
						switch(this._nMode){
							case "repeat":
								this.removeHackLayout();
								this._mode="repeat";
								c.setStyle(document.body,"backgroundImage",a);
								c.setStyle(document.body,"backgroundRepeat","repeat");
								c.setStyle(document.body,"backgroundPosition","0 0");
								break;
							case "center":
								this.removeHackLayout();
								this._mode="center";
								c.setStyle(document.body,"backgroundImage",a);
								c.setStyle(document.body,"backgroundRepeat","no-repeat");
								c.setStyle(document.body,"backgroundPosition","center center");
								break;
							case "centerRepeat":
								this.removeHackLayout();
								this._mode="centerRepeat";
								c.setStyle(document.body,"backgroundImage",a);
								c.setStyle(document.body,"backgroundRepeat","repeat");
								c.setStyle(document.body,"backgroundPosition","center center");
								break;
							case "zoom":
							case "adapt":
							case "fill":
								this.initHackLayer(),
								this._mode=this._nMode,
								this.isHackLayerNeeded()?(
									c.setStyle(this._zoomWallpaperContainer,"display","none"),
									this.zoomWallpaper(),
									c.setStyle(document.body,"background","none")
								):(
									c.setStyle(document.body,"backgroundImage",a),
									c.setStyle(document.body,"backgroundRepeat","no-repeat"),
									c.addClass(document.body,"wallpaperCss3"+this._mode)
								)
						}
					},
					setWallpaperSize:function(){
						var a=alloy.layout.getDesktopHeight(),
							b=alloy.layout.getDesktopWidth(),
							d=this._wallpaper.height,
							e=this._wallpaper.width,
							f=b*d/e,
							g=a*e/d;
						c.setStyle(this._zoomWallpaperContainer,"height",a+"px");
						c.setStyle(this._zoomWallpaperContainer,"width",b+"px");
						switch(this._mode){
							case "zoom":
								c.setStyle(this._zoomWallpaperContext,"height",a+"px");
								c.setStyle(this._zoomWallpaperContext,"width",b+"px");
								break;
							case "adapt":
								e/d>b/a?(
									c.setStyle(this._zoomWallpaperContext,"height",Math.round(f)+"px"),
									c.setStyle(this._zoomWallpaperContext,"width",b+"px"),
									c.setStyle(this._zoomWallpaperContext,"top",Math.floor((a-f)/2)+"px"),
									c.setStyle(this._zoomWallpaperContext,"left","0")
								):(
									c.setStyle(this._zoomWallpaperContext,"height",a+"px"),
									c.setStyle(this._zoomWallpaperContext,"width",Math.round(g)+"px"),
									c.setStyle(this._zoomWallpaperContext,"left",Math.floor((b-g)/2)+"px"),
									c.setStyle(this._zoomWallpaperContext,"top","0")
								);
								break;
							case "fill":
								e/d>b/a?(
									c.setStyle(this._zoomWallpaperContext,"height",a+"px"),
									c.setStyle(this._zoomWallpaperContext,"width",Math.ceil(g)+"px"),
									c.setStyle(this._zoomWallpaperContext,"left",Math.floor((b-g)/2)+"px"),
									c.setStyle(this._zoomWallpaperContext,"top","0")
								):(
									c.setStyle(this._zoomWallpaperContext,"height",Math.ceil(f)+"px"),
									c.setStyle(this._zoomWallpaperContext,"width",b+"px"),
									c.setStyle(this._zoomWallpaperContext,"top",Math.floor((a-f)/2)+"px"),
									c.setStyle(this._zoomWallpaperContext,"left","0")
								)
						}
					},
					zoomWallpaper:function(){
						this._mode=="zoom"&&(
							c.setStyle(this._zoomWallpaperContext,"top","0"),
							c.setStyle(this._zoomWallpaperContext,"left","0")
						);
						this.setWallpaperSize();
						c.setStyle(this._zoomWallpaperContainer,"display","");
						this._zoomWallpaperContext.src=this._wallpaper.src
					},
					reset:function(){
						this.removeHackLayout();
						this._mode="repeat";
						b.browser.ie?(
							document.body.style.removeAttribute("backgroundImage"),
							document.body.style.removeAttribute("backgroundRepeat"),
							document.body.style.removeAttribute("backgroundPosition")
						):c.setStyle(document.body,"background","")
					}
			}),
			C=new b.Class({
				init:function(){
					this._oldStyleNode=c.id("skinStyleNode");
					this._cacheStyle={}
				},
				getCurrentSkin:function(){
					return this._skin
				},
				applySkin:function(a){
					this._skin=a=this.getConfig(a);
					s(this._getPreloadImages(a.skinRoot,a.timeStamp),b.bind(this._onImagePreloaded,this))
				},
				getConfig:function(c){
					var d={
						name:"",
						timeStamp:"",
						window:{
							ie6WindowCenterBackground:"",
							ipadContainerBackColor:""
						},
						currentWindow:{
							ie6WindowCenterBackground:"",
							ipadContainerBackColor:""
						},
						skinRoot:""
					};
					if(b.isObject(c))
						d.id=(new Date).getTime(),
						d.name=c.name||"",
						d.timeStamp=c.timeStamp||"",
						d.window.ipadContainerBackColor=c.window.ipadContainerBackColor||"",
						d.window.ie6WindowCenterBackground=c.window.ie6WindowCenterBackground||"",
						d.currentWindow.ipadContainerBackColor=c.currentWindow.ipadContainerBackColor||"",
						d.currentWindow.ie6WindowCenterBackground=c.currentWindow.ie6WindowCenterBackground||"",
						d.skinRoot=c.skinRoot;
					else if(h[c]){
						b.extend(d,h[c]);
						var e=a[c];
						e||(e=alloy.util.getCdnUrlById(h[c].id)+"style/skin/"+c,a[c]=e);
						d.skinRoot=e
					}
					return d
				},
				applySkinStyle:function(a){
					if(this._newStyleNode)
						this._oldStyleNode&&c.getDocHead().removeChild(this._oldStyleNode),
						this._oldStyleNode=this._newStyleNode;
					this._newStyleNode=c.createStyleNode(a,"skinStyleNode"+v++)
				},
				_onImagePreloaded:function(){
					var a=this._cacheStyle[this._skin.id];
					if(!a){
						var a=this._skin,c;
						c=x;
						a=b.extend({},o,a);
						a=b.string.template(c,a);
						this._cacheStyle[this._skin.id]=a
					}
					this.applySkinStyle(a)
				},
				_getPreloadImages:function(a,c){
					return b.browser.ie==6||b.browser.ie==7?[]:[a+"/images/suggess_list_bg.png?t="+c,a+"/images/sprite_repeat_x_png.png?t="+c,a+"/images/sprite_main_png.png?t="+c]
				}
			}),
			y=new b.Class({
				init:function(){
					this.isInit=!0;
					this.curScene=null
				},
				getCurrentScene:function(){
					return this.curScene
				},
				applyScene:function(a){
					this.curScene&&this.closeScene();
					if(this.curScene=a)
						if(alloy.appconfig.getAllConfig(a))
							alloy.portal.runApp(a);
					else{
						this._iframeContainer=c.node(
							"div",
							{
								id:"sceneGrid",
								"class":"sceneGrid",
								style:"position:absolute;left:0;top:0;overflow:hidden;width:100%;height:100%;z-index:-1;"
							}
						);
						this._iframeContext=c.node("div");
						this._iframeContext.innerHTML='<iframe id ="iframeScene" frameborder="no" border="0" class ="iframeScene" allowtransparency="true" style ="position:absolute;left:0;top:0;overflow:hidden;width:100%;height:100%;background-color:transparent;"></iframe>';
						this._iframeContainer.appendChild(this._iframeContext);
						var b=c.id("zoomWallpaperGrid");
						b?alloy.layout.getDesktop().body.insertBefore(this._iframeContainer,b):alloy.layout.getDesktop().body.appendChild(this._iframeContainer);
						c.id("iframeScene").src=a
					}
				},
				closeScene:function(a){
					a=a||this.curScene;
					if(alloy.appconfig.getAllConfig(a))
						(a=alloy.portal.getApp(a))&&a.isRunning()&&a.exit();
					else if(a=c.id("sceneGrid"))
						c.id("iframeScene").src="domain.html",
						a.parentNode.removeChild(a)
				}
			}),
			z=new b.Class({
				init:function(){},
				getCurrentTheme:function(){
					return this._themeId
				},
				applyTheme:function(a,b){
					this._themeId=a;
					var c=this.getConfig(a),
						d=c.skin,
						e=c.scene,
						c=c.wallpaper;
					l.applyWallpaper(c.url,c.mode);
					j.applySkin(d);
					b||q.applyScene(e)
				},
				getConfig:function(a){
					if(b.isObject(a))
						return a;
					else if(d.themeConfig[a]){
						var c=d.themeConfig[a];
						c.wallpaper.url=c.wallpaper.url.indexOf("http://")>=0?c.wallpaper.url:alloy.util.getCdnUrlById(c.wallpaper.url.length)+"style/wallpaper/"+c.wallpaper.url;
						return d.themeConfig[a]
					}
					return{}
				}
			});
			this.applyTheme=function(a,c){
				b.browser.mobileSafari&&a=="theme_gravity"&&(a="theme_cloud");
				g.applyTheme(a,c)};
				this.setTheme=function(a){
					a.wallpaper.id="themeSetting_urlWallpaper";
					this.applyTheme(a);
					if(b.isObject(a)){
						a={};
						a.skin=j.getCurrentSkin();
						var c=l.getCurrentWallpaper(),
							c={
								id:"themeSetting_urlWallpaper",
								mode:l.getCurrentMode(),
								url:c
							};
						a.wallpaper=c;
						alloy.config.setCustomTheme(a)
					}else 
						d.themeConfig[a]&&alloy.config.setTheme(a)
				};
				this.getCurrentThemeID=function(){
					return g.getCurrentTheme()
				};
				this.applyWallpaper=function(a,b){
					l.applyWallpaper(a,b)
				};
				this.setWallpaper=function(a,b){
					l.applyWallpaper(a,b);
					/(\.jpg)|(\.jpeg)|(\.bmp)|(\.gif)|(\.png)$/i.test(a)||(b="iframe");
					var c={
						id:"themeSetting_urlWallpaper",
						mode:b,
						url:a
					},
					c={
						skin:j.getCurrentSkin(),
						wallpaper:c
					};
					alloy.config.setCustomTheme(c)
				};
				this.getCurrentWallpaper=function(){
					return l.getCurrentWallpaper()
				};
				this.resetWallpaper=function(){
					l.reset()
				};
				this.applySkin=function(a){
					j.applySkin(a)
				};
				this.setSkin=function(a){
					j.applySkin(a);
					a=l.getCurrentWallpaper();
					a={
						id:"themeSetting_urlWallpaper",
						mode:l.getCurrentMode(),
						url:a
					};
					a={
						skin:j.getCurrentSkin(),
						wallpaper:a
					};
					alloy.config.setCustomTheme(a)
				};
				this.applyScene=function(a){
					q.applyScene(a)
				};
				this.setScene=function(){};
				this.getCurrentSkin=function(){
					return j.getCurrentSkin()
				};
				this.init=function(){
					var a=c.id("skinTemplate");
					x=a.innerHTML;
					document.body.removeChild(a);
					g=new z;
					j=new C;
					l=new w;
					q=new y;
					e.addObserver(alloy.portal,"UACReady",H);
					e.addObserver(alloy.portal,"portalReady",F);
					typeof progress=="function"&&progress("themenanager init")
				};
				var F=function(){
					if(!alloy.config.getWallpaper().id){
						var a=alloy.config.getTheme().id,c=d.themeConfig[a].scene,a=0;
						if(b.browser.ie==6||b.browser.ie==7)
							a=500;
						setTimeout(function(){q.applyScene(c)},a)
					}
				},
				H=function(){
					if(alloy.portal.getUin()&&alloy.portal.getSkey()){
						var a=alloy.config.getTheme().id,
							b=alloy.config.getWallpaper().id,
							c=alloy.config.getWallpaper().mode,
							e=alloy.config.getWallpaper().url,
							f=alloy.config.getAppearance().id;
						b?(d.applyWallpaper(e,c),d.applySkin(f),d.applyScene()):d.applyTheme(a,!0)
					}else 
						p?r(p):n();
					p&&p.done&&d.themeArray.push(p)&&(p=null)
				},
				r=function(a){
					u=u||{id:"",mode:"repeat"};
					alloy.rpcService.selfSend(
						alloy.CONST.MAIN_URL+"web2/get_msg_tip?retype=1&tp=3",
						{
							method:"get",
							onSuccess:function(b){
								if(b.f==1)
									a.done=!0,u.id="theme_"+a.id;
								n()
							},
							onError:function(){n()}
						}
					)
				}
			}
		);