Jx().$package("alloy.rpcService",function(b){
		var d=this,
			c=b.dom,
			e=b.event,
			g,j,
			l=0,
			q,
			u=new b.Class(
				{
					init:function(a){this._ajaxRequestInstant=a},
					send:function(a,c){
						c=c||{};
						c.cacheTime=c.cacheTime||0;
						c.onSuccess=c.onSuccess||function(){};
						c.onError=c.onError||function(){};
						c.onTimeout=c.onTimeout||function(){};
						c.onComplete=c.onComplete||function(){};
						var d={
							method:c.method||"GET",
							contentType:c.contentType||"",
							enctype:c.enctype||"",
							data:c.data||{},
							param:c.param||{},
							arguments:c.arguments||{},
							context:c.context||null,
							timeout:c.timeout||3E4,
							onSuccess:function(a){
								var a=a.responseText||"-",d={};
								try{d=b.json.parse(a)}catch(e){b.error("alloy.rpcservice: JSON \u683c\u5f0f\u51fa\u9519","HttpRequest")}
								d.arguments=c.arguments||{};
								c.onSuccess.call(c.context,d)
							},
							onError:function(a){c.onError.call(c.context,a)},
							onTimeout:function(){var a={};a.arguments=c.arguments||{};c.onTimeout.call(c.context,a)},
							onComplete:function(){var a={};a.arguments=c.arguments||{};c.onComplete.call(c.context,a)}
						};
						alloy.portal.recoverCookie();
						d.data=b.string.toQueryString(d.data);
						if(d.method=="GET"){
							var e=d.data;
							c.cacheTime===0&&(e+=e?"&t="+(new Date).getTime():"t="+(new Date).getTime());
							e&&(a=a+"?"+e);
							d.data=null
						}else 
							d.contentType="application/x-www-form-urlencoded",a.indexOf("?");
						this._ajaxRequestInstant(a,d)
					}
				}
			),
			p=new b.Class(
				{
					init:function(a,f){
						var e="qqweb_proxySendIframe_"+a,g=this,h;
						this._ajaxCallbacks=[];
						this._proxyAjaxSend=this._proxySend=null;
						f+=(/\?/.test(f)?"&":"?")+"id="+a;
						b.out("ProxyRequest >>>>> init: "+f,"ProxyRequest");
						var j=function(){
							var a=window.frames[e];
							b.out("ProxyRequest >>>>> load: "+a.location.href,"ProxyRequest");
							try{
								if(a.ajax){
									g._proxyAjaxSend=a.ajax;
									for(var c=g._ajaxCallbacks,a=0,d=c.length;a<d;a++)
										g.proxySend(c[a].url,c[a].option);
									g._ajaxCallbacks=[]
								}else 
									b.warn("ProxyRequest >>>>> ajaxProxy error: ajax is undefined!!!!","ProxyRequest"),alloy.util.report2h("proxyrequest_error","start")
							}catch(f){
								b.error("ProxyRequest >>>>> ajaxProxy error: "+f.message+" !!!!","ProxyRequest"),alloy.util.report2h("proxyrequest_error2","start")
							}
						};
						h=document.body;
						var l=c.node("div",{"class":"hiddenIframe"});
						l.innerHTML='<iframe id="'+e+'" class="hiddenIframe" name="'+e+'" src="'+f+'" width="1" height="1"></iframe>';
						h.appendChild(l);
						h=c.id(e);
						this.id=a;
						this.onAjaxFrameLoad=j;
						d.onAjaxFrameLoad2=j;
						b.browser.firefox&&h.setAttribute("src",f)
					},
					send:function(a,b){
						this._proxyAjaxSend?(this.proxySend(a,b),this.send=this.proxySend):this._ajaxCallbacks.push({url:a,option:b})
					},
					proxySend:function(a,b){
						if(!this._proxySend)
							this._proxySend=new u(this._proxyAjaxSend);
						this._proxySend.send(a,b)
					}
				}
			),
			v=new b.Class(
				{
					init:function(){
						this._proxyArr={};
						this._proxyId=1
					},
					getProxyId:function(){
						return this._proxyId++
					},
					getProxy:function(a){
						var b=this._proxyArr[a];
						b||(b=new p(this.getProxyId(),a),this._proxyArr[a]=b);
						return b
					},
					getProxyById:function(a){
						for(var b in this._proxyArr)
							if(this._proxyArr[b].id==a)
								return this._proxyArr[b];
						return null
					}
				}
			);
		this.selfSend=function(a,c){
			g||(g=new u(b.http.ajax));
			g.send(a,c)
		};
		this.sSend=this.send=this.proxySend=function(a,b,c){
			j||(j=new v);
			c=c||alloy.CONST.API_PROXY_URL;
			c+=(/\?/.test(c)?"&":"?")+"callback=1";
			j.getProxy(c).send(a,b)
		};
		this.cgiSend=function(a,b,c){
			c=c||alloy.CONST.JAVA_CGI_PROXY_URL;
			d.proxySend(a,b,c)
		};
		this.psSend=function(a,b,c){
			c=c||alloy.CONST.PS_PROXY_URL;
			d.proxySend(a,b,c)
		};
		this.upSend=function(a,b,c){
			c=c||alloy.CONST.JAVA_UP_CGI_PROXY_URL;
			d.proxySend(a,b,c)
		};
		this.onAjaxFrameLoad=function(a){
			if(b.isUndefined(a))
				this.onAjaxFrameLoad2();
			else
				(a=j.getProxyById(a))&&a.onAjaxFrameLoad()
		};
		var x={
			_iframes:[],
			_tick:0,
			_select:function(){
				this._tick++;
				return this._iframes[(this._tick-1)%this._len]
			},
			init:function(a){
				if(this._isInit!=!0){
					this._len=a;
					for(var b=document.body,d,e=0;e<a;e++)
						d=c.node("div",{"class":"RPCService_hDiv"}),
						c.hide(d),
						d.innerHTML='<iframe id="RPCService_hIframe_'+e+'" name="RPCService_hIframe_'+e+'" src="'+alloy.CONST.MAIN_URL+'domain.html"></iframe>',
						b.appendChild(d),
						this._iframes[e]=[d,null,"RPCService_hIframe_"+e];
					this._isInit=!0
				}
			},
			take:function(a){
				var b=this._select();
				b[1]&&b[0].removeChild(b[1]);
				a.setAttribute("target",b[2]);
				b[1]=a;
				b[0].appendChild(a)
			}
		};
		this.formSend=function(a,b){
			x.init(2);
			var d={
					method:b.method||"GET",
					enctype:b.enctype||"",
					data:b.data||{},
					onSuccess:b.onSuccess||function(){},
					onError:b.onError||function(){},
					onComplete:b.onComplete||function(){},
					onTimeout:b.onTimeout||function(){},
					timeout:b.timeout?b.timeout:1E4
				},
				e=c.node(
					"form",
					{
						"class":"RPCService_form",
						method:d.method,
						action:a+"?t="+(new Date).getTime(),
						enctype:d.enctype
					}
				);
			if(Object.prototype.toString.call(d.data).indexOf("String")>-1){
				var g=c.node("input");
				g.type="text";
				g.name=d.data;
				e.appendChild(g)
			}else 
				for(var h in d.data)
					g=c.node("input"),
					g.type="text",
					g.name=h,
					g.setAttribute("value",d.data[h]),
					e.appendChild(g);
			x.take(e);
			e.submit()
		};
		this.sendGetVfWebQQ=function(a,c,d){
			alloy.portal.getTryUin()&&alloy.portal.getSkey()?(
				alloy.portal.speedTest.sRTS(1,"start",new Date),
				this.send(
					alloy.CONST.API_SERVER_URL+"get_vfwebqq2",
					{
						context:this,
						data:{},
						arguments:{uin:a},
						onSuccess:c||function(a){
							a.retcode===0&&a.result&&a.result.length===2&&a.result[0]=="vfwebqq"?(
								b.out(":GetVfWebQQSuccess..."),
								e.notifyObservers(this,"GetVfWebQQSuccess",a)
							):(
								b.out("[sendGetVfWebQQ\uff1a\u6570\u636e\u683c\u5f0f\u9519\u8bef] error: "+a.retcode+"-"+a.errmsg),
								e.notifyObservers(this,"GetVfWebQQError",a)
							);
							alloy.portal.speedTest.sRTS(1,"end",new Date,!0);
							alloy.portal.speedTest.sRTS(4,"start",new Date);
							alloy.portal.speedTest.sRTS(5,"start",new Date)
						},
						onError:d||function(a){
							b.out("\u83b7\u53d6\u4e00\u4e2a\u4eba\u7684\u767b\u5f55\u4fe1\u606f\u5931\u8d25");
							e.notifyObservers(this,"GetVfWebQQError",a);
							alloy.portal.speedTest.sRTS(1,"end",new Date,!0)
						}
					}
				)
			):e.notifyObservers(this,"GetVfWebQQError",{})
		};
		this.sendGetSeftInfo=function(a,c,d){
			alloy.portal.getTryUin()&&alloy.portal.getSkey()?(
				alloy.portal.speedTest.sRTS(1,"start",new Date),
				this.send(
					alloy.CONST.API_SERVER_URL+"get_self_info2",
					{
						context:this,
						data:{},
						arguments:{uin:a},
						timeout:2E4,
						onSuccess:c||function(a){
							a.retcode===0&&a.result?(
								alloy.util.report2qqweb("config|vfwebqq|success"),
								b.out(":GetVfWebQQSuccess..."),
								e.notifyObservers(this,"GetVfWebQQSuccess",a),
								e.notifyObservers(this,"GetUserInfoSuccess",a)
							):(
								b.out("[sendGetVfWebQQ\uff1a\u6570\u636e\u683c\u5f0f\u9519\u8bef] error: "+a.retcode+"-"+a.errmsg),
								e.notifyObservers(this,"GetVfWebQQError",a)
							);
							alloy.portal.speedTest.sRTS(1,"end",new Date,!0);
							alloy.portal.speedTest.sRTS(4,"start",new Date);
							alloy.portal.speedTest.sRTS(5,"start",new Date)
						},
						onError:d||function(a){
							b.out("\u83b7\u53d6\u4e00\u4e2a\u4eba\u7684\u767b\u5f55\u4fe1\u606f\u5931\u8d25");
							alloy.util.report2qqweb("config|vfwebqq|error");
							timeoutConfirm("\u83b7\u53d6\u4e2a\u4eba\u767b\u5f55\u4fe1\u606f\u5931\u8d25,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f(\u70b9\u51fb\u53d6\u6d88\u5c06\u4ee5\u6e38\u5ba2\u6001\u767b\u5f55)")||e.notifyObservers(this,"GetVfWebQQError",a);
							alloy.portal.speedTest.sRTS(1,"end",new Date,!0)
						},
						onTimeout:function(){
							alloy.util.report2qqweb("config|vfwebqq|timeout");
							timeoutConfirm("\u83b7\u53d6\u4e2a\u4eba\u767b\u5f55\u4fe1\u606f\u8d85\u65f6,\u662f\u5426\u5237\u65b0\u91cd\u8bd5\uff1f(\u70b9\u51fb\u53d6\u6d88\u5c06\u4ee5\u6e38\u5ba2\u6001\u767b\u5f55)")||e.notifyObservers(this,"GetVfWebQQError");
							alloy.util.report2h("get_vfwebqq","timeout")
						}
					}
				)
			):e.notifyObservers(this,"GetVfWebQQError",{})
		};
		var m,
			o=function(a,d){
				m=alloy.layout.messagebox('<div style="width:100%; height:100%; line-height:30px;">\t\t\t\t\t\t<div style ="text-align: left; padding-left: 10px;">\t\t\t\t\t\t\t<div>\u4e3a\u4e86\u60a8\u7684\u8d26\u53f7\u5b89\u5168\uff0c\u8bf7\u6267\u884c\u8eab\u4efd\u9a8c\u8bc1\uff0c\u5728\u8f93\u5165\u6846\u8f93\u5165\u4e0b\u56fe\u4e2d\u7684\u9a8c\u8bc1\u7801</div>\t\t\t\t\t\t\t<div>\u9a8c\u8bc1\u7801:&nbsp&nbsp<input id="verify_input_code" type="text" style="vertical-align:middle;" />&nbsp;&nbsp;<span id="buddyfinder_code_gf" style="color:red"></span></div>\t\t\t\t\t\t\t<img style="float:left;margin-right:10px" id="verify_img_code" src="" />\t\t\t\t\t\t\t<a style="display:inline;line-height:60px;" id="verify_a_code" alt="\u770b\u4e0d\u6e05\u6362\u4e00\u5f20" href="">\u770b\u4e0d\u6e05\u6362\u4e00\u5f20</a>\t\t\t\t\t\t\t<div id="verify_img_code_wrong" style="display:none;color:red;width:65px;">\u9a8c\u8bc1\u7801\u9519\u8bef</div>\t\t\t\t\t\t</div>\t\t\t\t\t</div>',
					{
						title:"\u8eab\u4efd\u9a8c\u8bc1",
						resize:!0,
						width:380,
						height:123,
						hasOkButton:!0,
						windowType:"EqqWindow",
						isSetCentered:!0
					}
				);
				var g=c.id("verify_img_code"),
					h=c.id("verify_a_code"),
					j=c.id("verify_input_code"),
					l=null;
				e.on(
					g,
					"load",
					function(){
						l=b.cookie.get("verifysession",alloy.CONST.MAIN_DOMAIN)
					}
				);
				e.on(
					h,
					"click",
					function(a){
						a.preventDefault();
						c.id("verify_img_code").src="http://captcha.qq.com/getimage?aid=1003901&"+Math.random()
					}
				);
				e.addObserver(
					m,
					"clickOkButton",
					function(){
						var b=j.value;
						if(b&&l)
							return d(a,b,l),!1;
						j.focus();
						c.id("verify_input_code").innerHTML="\u8bf7\u5148\u8f93\u5165\u9a8c\u8bc1\u7801\uff01";
						return!1
					}
				);
				j.focus();
				e.on(
					j,
					"keydown",
					function(a){
						a.keyCode==13&&e.notifyObservers(m,"clickOkButton")&&setTimeout(function(){m.close()},0)
					}
				);
				c.id("verify_img_code").src="http://captcha.qq.com/getimage?aid=1003901&"+Math.random()
			};
		this.sendGetUserInfo=function(a,b,g,h){
			this.send(
				alloy.CONST.API_SERVER_URL+"get_friend_info2",
				{
					context:this,
					data:{
						tuin:a,
						verifysession:g||"",
						code:b||"",
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					arguments:{uin:a},
					onSuccess:function(b){
						b.retcode===0?(
							setTimeout(function(){try{m&&m.close()}catch(a){}},0),
							h?h.call(this,b):e.notifyObservers(this,"GetUserInfoSuccess",b)
						):b.retcode===1E3?o(
							a,
							function(a,b,c){
								d.sendGetUserInfo(a,b,c,h)
							}
						):b.retcode===1001?(
							c.id("verify_img_code_wrong").style.display="inline",
							c.id("verify_img_code").src="http://captcha.qq.com/getimage?aid=1003901&"+Math.random(),
							c.id("verify_input_code").value="",
							c.id("verify_input_code").focus()
						):(setTimeout(function(){try{m&&m.close()}catch(a){}},0),
							e.notifyObservers(this,"GetUserInfoError",b)
						)
					},
					onError:function(a){e.notifyObservers(this,"GetUserInfoError",a)}
				}
			)
		};
		this.sendGetSingleInfo=function(a,b,g,h){
			!b||!g?o(
						a,
						function(a,b,c){
							d.sendGetSingleInfo(a,b,c,h)
						}
					):this.send(
						alloy.CONST.API_SERVER_URL+"get_single_info2",
						{
							context:this,
							data:{
								tuin:a,
								verifysession:g||"",
								code:b||"",
								vfwebqq:alloy.portal.getVfWebQQ()
							},
							arguments:{uin:a},
							onSuccess:function(b){
								b.retcode===0?(
												b.result.uin=b.result.tuin,
												setTimeout(function(){try{m&&m.close()}catch(a){}},0),
												h?h.call(this,b):e.notifyObservers(this,"GetUserInfoSuccess",b)
											):b.retcode===1E3?o(
																a,
																function(a,b,c){d.sendGetSingleInfo(a,b,c,h)}
															):b.retcode===1001?(
																				c.id("verify_img_code_wrong").style.display="inline",
																				c.id("verify_img_code").src="http://captcha.qq.com/getimage?aid=1003901&"+Math.random(),
																				c.id("verify_input_code").value="",
																				c.id("verify_input_code").focus()
																			):(
																				setTimeout(function(){try{m&&m.close()}catch(a){}},0),
																				e.notifyObservers(this,"GetUserInfoError",b)
																			)
							},
							onError:function(a){e.notifyObservers(this,"GetUserInfoError",a)}
						}
					)
		};
		this.sendGetUserInfo_with_code=function(a,f,g,h,j){
			f=f||"";
			this.send(
				alloy.CONST.API_SERVER_URL+"get_stranger_info2",
				{
					context:this,
					data:{
						tuin:a,
						verifysession:g||"",
						gid:0,
						code:f,
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					arguments:{uin:a,code:f},
					onSuccess:h||function(b){
						b.retcode===0?(
							setTimeout(function(){try{m&&m.close()}catch(a){}},0),
							h&&h.call(this,b),
							e.notifyObservers(this,"GetUserInfoSuccess",b)
						):b.retcode===1E3?o(
							a,
							function(a,b,c){d.sendGetUserInfo_with_code(a,b,c)}
						):b.retcode===1001?(
							c.id("verify_img_code_wrong").style.display="inline",
							c.id("verify_img_code").src="http://captcha.qq.com/getimage?aid=1003901&"+Math.random(),
							c.id("verify_input_code").value="",
							c.id("verify_input_code").focus()
						):(
							setTimeout(function(){try{m&&m.close()}catch(a){}},0),
							e.notifyObservers(this,"GetUserInfoError",b)
						)
					},
					onError:j||function(a){
						b.out("\u83b7\u53d6\u4e00\u4e2a\u4eba\u7684\u4fe1\u606f\u5931\u8d25");
						e.notifyObservers(this,"GetUserInfoError",a)
					}
				}
			)
		};
		this.sendGetFriendUin2=function(a,f,g,h,j,l){
			this.send(
				alloy.CONST.API_SERVER_URL+"get_friend_uin2",
				{
					context:this,
					data:{
						tuin:a,
						verifysession:j||"",
						type:f,
						code:h||"",
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					arguments:{uin:a},
					onSuccess:function(b){
						b.retcode===0?(
							l||setTimeout(function(){try{m&&m.close()}catch(a){}},0),
							g&&g(b),
							e.notifyObservers(this,"GetFriendUinSuccess",b)
						):b.retcode===1E3?o(
							a,
							function(a,b,c){d.sendGetFriendUin2(a,f,g,b,c)}
						):b.retcode===1001?(
							c.id("verify_img_code_wrong").style.display="inline",
							c.id("verify_img_code").src="http://captcha.qq.com/getimage?aid=1003901&"+Math.random(),
							c.id("verify_input_code").value="",
							c.id("verify_input_code").focus()
						):(
							setTimeout(function(){try{m&&m.close()}catch(a){}},0),
							e.notifyObservers(this,"GetFriendUinError",b)
						)
					},
					onError:function(a){
						b.out("\u83b7\u53d6\u4e00\u4e2a\u4eba\u7684uin\u5931\u8d25");
						e.notifyObservers(this,"GetFriendUinError",a)
					}
				}
			)
		};
		this.sendModifyMyDetails=function(a){
			a.vfwebqq=alloy.portal.getVfWebQQ();
			this.send(
				alloy.CONST.API_SERVER_URL+"modify_my_details2",
				{
					context:this,
					method:"POST",
					data:{r:b.json.stringify(a)},
					arguments:{},
					onSuccess:function(a){
						a.retcode===0?(
							b.out(":ModifyMyDetailsSuccess..."),
							e.notifyObservers(this,"ModifyMyDetailsSuccess",a)
						):(
							b.out("[sendModifyMyDetails\uff1a\u6570\u636e\u683c\u5f0f\u9519\u8bef] error: "+a.retcode+"-"+a.errmsg),
							e.notifyObservers(this,"ModifyMyDetailsError",a)
						)
					},
					onError:function(a){
						b.out("\u4fee\u6539\u81ea\u5df1\u7684\u7684\u8be6\u7ec6\u8d44\u6599\u5931\u8d25");
						e.notifyObservers(this,"ModifyMyDetailsError",a)
					}
				}
			)
		};
		this.sendModifyMyAvatar=function(a){
			a.vfwebqq=alloy.portal.getVfWebQQ();
			this.send(
				alloy.CONST.API_SERVER_URL+"modify_my_head",
				{
					context:this,
					method:"POST",
					data:{r:b.json.stringify(a)},
					arguments:{},
					onSuccess:function(a){a.retcode===0?e.notifyObservers(this,"ModifyMyAvatarSuccess",a):e.notifyObservers(this,"ModifyMyAvatarError",a)},
					onError:function(a){e.notifyObservers(this,"ModifyMyAvatarError",a)}
				}
			)
		};
		this.sendGetGroupInfoByGid=function(a){
			this.send(
				alloy.CONST.API_SERVER_URL+"get_group_info_ext2",
				{
					context:this,
					data:{
						gcode:a,
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					arguments:{gcode:a},
					onSuccess:function(a){
						a.retcode===0?(
							b.out(":GetUserInfoSuccess..."),
							e.notifyObservers(this,"GetGroupInfoByGidSuccess",a)
						):(
							b.out("[sendGetUserInfo\uff1a\u6570\u636e\u683c\u5f0f\u9519\u8bef] error: "+a.retcode+"-"+a.errmsg),
							e.notifyObservers(this,"GetGroupInfoByGidError",a)
						)
					},
					onError:function(a){
						b.out("\u83b7\u53d6\u7fa4\u7684\u4fe1\u606f\u5931\u8d25");
						e.notifyObservers(this,"GetUserInfoError",a)
					}
				}
			)
		};
		this.sendGetGroupPublicInfo=function(a,c,d,g){
			this.send(
				alloy.CONST.API_SERVER_URL+"get_group_public_info2",
				{
					context:this,
					data:{
						gcode:a,
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					arguments:c||{gcode:a},
					onSuccess:d||function(a){
						a.retcode===0?(
							b.out(":GetGroupPublicInfoSuccess..."),
							e.notifyObservers(this,"GetGroupPublicInfoSuccess",a)
						):(
							b.out("[GetGroupPublicInfoError\uff1a\u6570\u636e\u683c\u5f0f\u9519\u8bef] error: "+a.retcode+"-"+a.errmsg),
							e.notifyObservers(this,"GetGroupPublicInfoError",a)
						)
					},
					onError:g||function(a){
						b.out("\u83b7\u53d6\u7fa4\u7684\u516c\u5171\u4fe1\u606f\u5931\u8d25");
						e.notifyObservers(this,"GetGroupPublicInfoError",a)
					}
				}
			)
		};
		this.sendGetGCardInfo=function(a){
			this.send(
				alloy.CONST.API_SERVER_URL+"get_self_business_card2",
				{
					context:this,
					data:{
						gcode:a,
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					arguments:{gcode:a},
					onSuccess:function(a){
						a.retcode===0?(
							b.out(":GetGCardInfoSuccess..."),
							e.notifyObservers(this,"GetGCardInfoSuccess",a)
						):(
							b.out("[sendGetUserInfo\uff1a\u6570\u636e\u683c\u5f0f\u9519\u8bef] error: "+a.retcode+"-"+a.errmsg),
							e.notifyObservers(this,"GetGCardInfoError",a)
						)
					},
					onError:function(a){
						b.out("\u83b7\u53d6\u7fa4\u7684\u4fe1\u606f\u5931\u8d25");
						e.notifyObservers(this,"GetGCardInfoError",a)
					}
				}
			)
		};
		this.sendGetBuddyList=function(a,c,d){
			a=a||{};
			a.vfwebqq=alloy.portal.getVfWebQQ();
			alloy.portal.speedTest.sRTS(3,"start",new Date);
			this.send(
				alloy.CONST.API_SERVER_URL+"get_user_friends2",
				{
					context:this,
					arguments:a,
					method:"POST",
					data:{r:b.json.stringify(a)},
					onSuccess:c||function(a){
						if(a.retcode===0){
							for(var c=a.result.categories||[],d=!1,f=0;f<c.length;f++)
								c[f].index==0&&(d=!0);
							d||c.unshift({index:0,name:"\u6211\u7684\u597d\u53cb"});
							b.out(":GetBuddyListSuccess...1");
							e.notifyObservers(this,"GetBuddyListSuccess",a.result);
							b.out(":GetBuddyListSuccess...2")
						}else 
							b.out("[sendGetBuddyList] error: "+a.retcode+"-"+a.errmsg),
								e.notifyObservers(this,"GetBuddyListError",a),
								b.out("[sendGetBuddyList] error: end")
					},
					onError:d||function(a){
						b.out("\u597d\u53cb\u5217\u8868\u5931\u8d25");
						e.notifyObservers(this,"GetBuddyListError",a)
					}
				}
			)
		};
		this.sendBatchGetVipInfo=function(a,c,d,g){
			param={};
			param.ul=b.json.stringify(a);
			param.vfwebqq=alloy.portal.getVfWebQQ();
			this.send(
				alloy.CONST.API_SERVER_URL+"batch_get_vipinfo",
				{
					context:this,
					arguments:c||param,method:"POST",
					data:param,
					onSuccess:d||function(a){
						a.retcode===0?e.notifyObservers(this,"BatchGetVipInfoSuccess",a.result):(
							b.out("\u6279\u91cf\u62c9\u53d6\u4f1a\u5458\u4fe1\u606f\u5931\u8d25"),
							e.notifyObservers(this,"BatchGetVipInfoError",a)
						)
					},
					onError:g||function(a){
						b.out("\u6279\u91cf\u62c9\u53d6\u4f1a\u5458\u4fe1\u606f\u51fa\u9519");
						e.notifyObservers(this,"BatchGetVipInfoError",a)
					}
				}
			)
		};
		this.sendGetGroupList=function(a,c,d){
			a=a||{};
			a.vfwebqq=alloy.portal.getVfWebQQ();
			this.send(
				alloy.CONST.API_SERVER_URL+"get_group_name_list_mask2",
				{
					context:this,
					arguments:a,
					method:"POST",
					data:{r:b.json.stringify(a)},
					onSuccess:c||function(a){
						a.retcode===0?(
							e.notifyObservers(this,"GetGroupListSuccess",a.result),
							b.out(":GetGroupListSuccess...")
						):(
							b.out("[sendGetGroupList] error: "+a.retcode+"-"+a.errmsg),
							e.notifyObservers(this,"GetGroupListError",a)
						)
					},
					onError:d||function(a){
						b.out("\u7fa4\u5217\u8868\u5931\u8d25");
						e.notifyObservers(this,"GetGroupListError",a)
					}
				}
			)
		};
		this.sendGetRecentList=function(a,c,d){
			a=a||{};
			a.vfwebqq=alloy.portal.getVfWebQQ();
			this.send(
				alloy.CONST.API_SERVER_URL+"get_recent_contact2",
				{
					context:this,
					method:"POST",
					data:{r:b.json.stringify(a)},
					onSuccess:c||function(a){
						a.retcode===0?(
							e.notifyObservers(this,"GetRecentListSuccess",a.result),
							b.out(":GetRecentListSuccess...")
						):(
							b.out("[sendGetRecentList] error: "+a.retcode+"-"+a.errmsg),
							e.notifyObservers(this,"GetRecentListError",a)
						)
					},
					onError:d||function(a){
						b.out("\u6700\u8fd1\u8054\u7cfb\u4eba\u5217\u8868\u5931\u8d25");
						e.notifyObservers(this,"GetRecentListError",a)
					}
				}
			)
		};
		this.sendChangeGroupMask=function(){};
		this.sendGetGroupInfo=function(a,c,d){
			a=a||{};
			a.vfwebqq=alloy.portal.getVfWebQQ();
			this.send(
				alloy.CONST.API_SERVER_URL+"get_group_info_ext2",
				{
					context:this,
					data:a,
					arguments:a,
					onSuccess:c||function(a){
						a.retcode===0?(
							b.out(":GetGroupInfoSuccess 1..."),
							e.notifyObservers(this,"GetGroupInfoSuccess",a.result),
							b.out(":GetGroupInfoSuccess 2...")
						):(
							b.out("[sendGetGroupInfo] error: "+a.retcode+"-"+a.errmsg),
							e.notifyObservers(this,"GetGroupInfoError",a)
						)
					},
					onError:d||function(a){
						b.out("\u7fa4\u8d44\u6599\u5931\u8d25");
						e.notifyObservers(this,"GetGroupInfoError",a)
					}
				}
			)
		};
		this.sendGetQQAllow=function(a,b){
			this.send(
				alloy.CONST.API_SERVER_URL+"get_allow_info2",
				{
					context:this,
					method:"GET",
					data:{
						tuin:a,
						retainKey:"allow",
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					arguments:{uin:a},
					onSuccess:b||function(){},
					onError:function(){}
				}
			)
		};
		this.sendGetQQLevel=function(a){
			this.send(
				alloy.CONST.API_SERVER_URL+"get_qq_level2",
				{
					context:this,
					method:"GET",
					data:{
						tuin:a,
						vfwebqq:alloy.portal.getVfWebQQ()
					},
					arguments:{uin:a},
					onSuccess:function(a){
						a.retcode===0?(
							b.out(":GetQQLevelSuccess 1..."),
							e.notifyObservers(d,"GetQQLevelSuccess",a),
							b.out(":GetQQLevelSuccess 2...")
						):(
							b.out("[sendGetQQLevel] error: "+a.retcode+"-"+a.errmsg),
							e.notifyObservers(d,"GetQQLevelError",a)
						)
					},
					onError:function(a){
						b.out("QQ\u7b49\u7ea7\u62c9\u53bb\u5931\u8d25");
						e.notifyObservers(d,"GetQQLevelError",a)
					}
				}
			)
		};
		this.sendSetSignature=function(a){alloy.rpcService.send(alloy.CONST.API_SERVER_URL+"set_long_nick2",{context:d,method:"POST",data:{r:b.json.stringify({nlk:a,vfwebqq:alloy.portal.getVfWebQQ()})},arguments:{nlk:a},onSuccess:function(c){c.retcode===0?e.notifyObservers(d,"SetBuddySignatureSuccess",a):(e.notifyObservers(d,"SetBuddySignatureError",a),b.error("[sendSetSelfSignature] error: "+c.retcode+"-"+c.errmsg))}})};this.sendGetSignature=function(a){this.send(alloy.CONST.API_SERVER_URL+"get_single_long_nick2",{context:this,method:"GET",data:{tuin:a,vfwebqq:alloy.portal.getVfWebQQ()},arguments:{uin:a},onSuccess:function(a){a.retcode===0?e.notifyObservers(d,"GetBuddySignatureSuccess",a):b.out("[sendGetSignature] error: "+a.retcode+"-"+a.errmsg)},onError:function(){b.out(" sendGetSignatureError")}})};this.sendGetMultiSignature=function(a){this.send(alloy.CONST.API_SERVER_URL+"get_long_nick",{context:this,method:"GET",data:{tuin:a,vfwebqq:alloy.portal.getVfWebQQ()},onSuccess:function(a){a.retcode===0?e.notifyObservers(d,"GetMultiBuddySignatureSuccess",a):b.out("[sendGetSignature] error: "+a.retcode+"-"+a.errmsg)},onError:function(){b.out(" sendGetSignatureError")}})};this.sendGetTipsInfo=function(a){a=a||{};alloy.rpcService.selfSend(alloy.CONST.MAIN_URL+"web2/get_msg_tip",{context:d,method:"GET",data:{uin:a.uin||"",tp:a.tp||1,id:a.id||0,retype:a.retype||1,rc:a.rc||0,lv:alloy.portal.getLoginLevel()||""},onSuccess:a.onSuccess?a.onSuccess:function(a){a.c===0?e.notifyObservers(d,"GetTipsInfoSuccess",a):a.c!==1&&b.error("[sendGetTipsInfo] error!")}})};this.sendQuitGroup=function(a){a.vfwebqq=alloy.portal.getVfWebQQ();alloy.rpcService.send(alloy.CONST.API_SERVER_URL+"quit_group2",{context:this,method:"POST",data:{r:b.json.stringify(a)},arguments:a,onSuccess:function(a){a.retcode===0?(b.out(":sendQuitGroup..."),e.notifyObservers(alloy.rpcService,"sendQuitGroupSuccess",a)):(b.out("[sendModifyMyDetails\uff1a\u6570\u636e\u683c\u5f0f\u9519\u8bef] error: "+a.retcode+"-"+a.errmsg),e.notifyObservers(alloy.rpcService,"sendQuitGroupError",a))},onError:function(a){b.out("\u9000\u51fa\u5931\u8d25");e.notifyObservers(alloy.rpcService,"sendQuitGroupError",a)}})};this.getAppInfo=function(a,c,d,e){a={appid:parseInt(a),loadMethod:0};if(c)a.val=c;a.vfwebqq=alloy.portal.getVfWebQQ();alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/market/getappinfo.do",{context:a.context||this,method:"GET",data:{appattrib:b.json.stringify(a)},arguments:a,onSuccess:d||function(){},onError:e||function(){}})};this.setAppVote=function(a,c,g){alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"cgi/qqweb/market/updateapphot.do",{context:a.context||this,method:"POST",data:{appattrib:b.json.stringify(a),vfwebqq:alloy.portal.getVfWebQQ()},arguments:a,onSuccess:c||function(){},onError:g||function(a){b.out("\u5e94\u7528\u8bc4\u5206\u5931\u8d25");e.notifyObservers(d,"SetAppVoteError",a)}})};this.createAppComment=function(a,b,c){a.ni=a.ni||alloy.portal.getPortalSelf("nick")||alloy.portal.getPortalSelf("uin");a.vfwebqq=alloy.portal.getVfWebQQ();alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"cgi/qqweb/market/createappcomment.do",{context:a.context||this,method:"POST",data:a,arguments:a,onSuccess:b||function(){},onError:c||function(){}})};this.createAppComplain=function(a,c,d){a.ni=a.ni||alloy.portal.getPortalSelf("nick")||alloy.portal.getPortalSelf("uin");a.vfwebqq=alloy.portal.getVfWebQQ();alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"cgi/qqweb/market/appusercomplain.do",{context:a.context||this,method:"POST",data:{appattrib:b.json.stringify(a)},arguments:a,onSuccess:c||function(){},onError:d||function(){}})};this.sendSetConfig=function(a){a.data.vfwebqq=alloy.portal.getVfWebQQ();var c=a.action||"set";a.data&&a.data.r&&(a.data.r=b.json.stringify(a.data.r));this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/newuac/"+c+".do",{method:"POST",data:a.data,onSuccess:a.onSuccess,context:a.context})};this.sendMessageFilterConfig=function(a){a.data.vfwebqq=qqweb.portal.getVfWebQQ();this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/uac/messagefilter.do",{method:"POST",data:a.data,onSuccess:a.onSuccess,context:a.context})};this.sendSetConfigNew=function(a){this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/newuac/"+(a.action||"set")+".do",{method:"POST",data:{r:b.json.stringify(a.data),vfwebqq:alloy.portal.getVfWebQQ()},arguments:a.arguments,onSuccess:a.onSuccess,context:a.context})};this.sendMSetConfig=function(a){this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/newuac/mset.do",{method:"POST",data:{r:b.json.stringify(a.data),vfwebqq:alloy.portal.getVfWebQQ()},onSuccess:a.onSuccess,context:a.context})};var h=function(){q&&(d.sendMSetConfig({data:q}),q=null)};this.sendMSetConfigDelay=function(a){l&&clearTimeout(l);q=q||{};var b=a.data,c;for(c in b){q[c]=q[c]||{};for(var d in b[c])q[c][d]=b[c][d]}l=setTimeout(h,a.delay||5E3)};this.sendGetConfig=function(a){a.data=a.data||{};a.data.uin=qqweb.portal.getUin();a.data&&a.data.r&&(a.data.r=b.json.stringify(a.data.r));this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/newuac/"+a.action+".do",{data:a.data,arguments:a.arguments,method:"POST",timeout:2E4,onSuccess:a.onSuccess,onError:a.onError,onComplete:a.onComplete,onTimeout:a.onTimeout,context:a.context})};this.sendGetAllConfig=function(a){a.data=a.data||{};a.data.uin=alloy.portal.getUin();a.data&&a.data.r&&(a.data.r=b.json.stringify(a.data.r));this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/newuac/getall.do",{data:a.data,arguments:a.arguments,method:"POST",onSuccess:a.onSuccess,context:a.context})};this.sendGetNewAppCount=function(){var a={};this.cgiSend(alloy.CONST.JAVA_CGI_URL+"cgi/qqweb/market/getnewappnumber.do",{context:this,method:"GET",data:{r:'{"appid":1000000,"type":[1,-1]}'},onSuccess:function(b){b.retcode===0?e.notifyObservers(alloy.rpcService,"SendGetNewAppCountSuccess",b):e.notifyObservers(alloy.rpcService,"SendMsgError",{uin:a.to,retcode:b.retcode,errmsg:b.errmsg})},onError:function(){}})};this.sendGetDefaultAppIntroduce=function(a,c,g){alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/market/getdefaultappinfo.do",{context:d,method:"POST",data:{appattrib:b.json.stringify(a),vfwebqq:alloy.portal.getVfWebQQ()},arguments:a,onSuccess:c||function(a){a.retcode===0?onGetAppIntroduceSuccess(a.result.resultData):b.out("\u5e94\u7528\u4ecb\u7ecd\u62c9\u53d6\u5931\u8d25"+a.errmsg)},onError:g||function(a){b.out("\u5e94\u7528\u62c9\u53d6\u5931\u8d25");e.notifyObservers(d,"GetAppIntroduceError",a)}})};this.sendReport=function(a){alloy.rpcService.formSend("http://tj.qstatic.com/log",{method:"POST",data:{r:b.string.trim(a)}})};this.reportQstatic=function(a){qqweb.util.report2qqweb(a)};this.sendSearchGroup=function(a){a.data.vfwebqq=qqweb.portal.getVfWebQQ();this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/group/search.do",{data:a.data,arguments:a.data,onSuccess:a.onSuccess,onError:a.onError,context:a.context})};this.sendGetGroupLog2=function(a,c,g){var h,j;a.mode==1?(h=a.lastbs?a.lastbs-a.ps:0,j=a.lastbs?a.lastbs-1:0):a.mode==2&&(h=a.lastes?a.lastes+1:0,j=a.lastes?a.lastes+a.ps:0);h={ps:a.ps,bs:h,es:j,gid:a.gcode,mode:a.mode,vfwebqq:qqweb.portal.getVfWebQQ()};this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/top/groupchatlog",{context:this,data:h,arguments:{gid:a.gid,gcode:a.gcode},onSuccess:c||function(a){e.notifyObservers(d,"SendGetGroupLogSuccess",a)},onError:g||function(){b.out("[SendGetGroupLog] error")}})};this.sendGetGroupLogDates=function(a,c,d){a.vfwebqq=qqweb.portal.getVfWebQQ();this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/top/chatlogdates",{context:this,data:a,onSuccess:c||function(){},onError:d||function(){b.out("[SendGetGroupLog] error")}})};this.sendGetDiscuLog=function(a,c,d){var e={p:a.p,gid:a.did.slice(1),c:a.c,ty:2,vfwebqq:qqweb.portal.getVfWebQQ()};this.cgiSend(alloy.CONST.JAVA_CGI_URL+"cgi/top/get_one_page",{context:this,data:e,arguments:{did:a.did,p:a.p,c:a.c},onSuccess:c||function(){},onError:d||function(){b.out("[SendGetGroupLog] error")}})};this.sendGetGroupLogByTime=function(a,c,g){arguments={gid:a.gid,gcode:a.gcode};var h=a;h.gid=a.gcode;h.vfwebqq=qqweb.portal.getVfWebQQ();this.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/group/uintimechatlog.do",{context:this,data:h,arguments:arguments,onSuccess:c||function(a){e.notifyObservers(d,"sendGetGroupLogByTime",a)},onError:g||function(){b.out("[SendGetGroupLog] error")}})};this.reportAppRun=function(a){a={appid:0,rappid:parseInt(a)};alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"cgi/qqweb/market/record.do",{context:a.context||this,method:"POST",data:{appattrib:b.json.stringify(a),vfwebqq:alloy.portal.getVfWebQQ()},arguments:a})};this.reportAppShare=function(a){a={type:parseInt(a.type),appid:parseInt(a.appId)};alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"cgi/qqweb/market/appshare.do",{context:a.context||this,method:"POST",data:{appattrib:b.json.stringify(a),vfwebqq:alloy.portal.getVfWebQQ()},arguments:a})};this.sendGetAPISkey=function(a){a=a||{};alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"cgi/qqweb/app/loadapp.do",{context:d,method:"GET",data:{r:b.json.stringify({appid:a.appid})},timeout:1E4,onSuccess:a.onSuccess,onError:a.onError,onTimeout:a.onTimeout})};this.sendCheckHack=function(a){alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"/check.php",{context:d,method:"POST",data:{k:a.key},onSuccess:a.onSuccess})};this.sendGetVipConfig=function(a,b,c){if(alloy.portal.getLoginLevel()>alloy.CONST.LOGIN_LEVEL_NONE){var g={level:a.level};g.vfwebqq=qqweb.portal.getVfWebQQ();this.send(alloy.CONST.API_SERVER_URL+"get_vipconfig",{context:a.context||this,data:g,onSuccess:b||function(a){a.retcode===0&&a.result?e.notifyObservers(d,"GetVipConfigSuccess",a):e.notifyObservers(d,"GetVipConfigError")},onError:c||function(){e.notifyObservers(d,"GetVipConfigError")},onTimeout:function(){e.notifyObservers(d,"GetVipConfigError")}})}};this.sendSetVipConfig=function(a,c,g){if(alloy.portal.getLoginLevel()>alloy.CONST.LOGIN_LEVEL_NONE){var h={};h.vfwebqq=qqweb.portal.getVfWebQQ();h.roamall=a.roamall||0;if(a.setuinlist&&a.setuinlist.length)h.setuinlist=b.json.stringify(a.setuinlist);if(a.unsetuinlist&&a.unsetuinlist.length)h.unsetuinlist=b.json.stringify(a.unsetuinlist);this.send(alloy.CONST.API_SERVER_URL+"set_vipconfig",{context:a.context||this,method:"POST",arguments:a.arguments,data:h,onSuccess:c||function(a){a.retcode===0&&a.result?e.notifyObservers(d,"SetVipConfigSuccess",a):e.notifyObservers(d,"SetVipConfigError",a)},onError:g||function(a){e.notifyObservers(d,"SetVipConfigError",a)},onTimeout:function(){e.notifyObservers(d,"SetVipConfigError",data)}})}};this.getAppInfoMulti=function(a){var c={appid:a.appList,loadMethod:4};alloy.rpcService.cgiSend(alloy.CONST.JAVA_CGI_URL+"keycgi/qqweb/market/getappinfo.do",{context:c.context||this,method:"GET",data:{appattrib:b.json.stringify(c)},arguments:c,onSuccess:a.onSuccess||function(){},onError:a.onError||function(){},onTimeout:a.onError||function(){}})};this.sendGetRecentChat=function(a){this.send(alloy.CONST.API_SERVER_URL+"recent_chat",{context:this,method:"GET",timeout:1E4,data:{vfwebqq:alloy.portal.getVfWebQQ()},onSuccess:a.onSuccess,onError:a.onError})};this.sendFileErrorReport=function(a){this.cgiSend(alloy.CONST.JAVA_CGI_URL+"cgi/top/save_logs",{context:d,method:"POST",data:{logdata:b.json.stringify(a),vfwebqq:alloy.portal.getVfWebQQ()}})}});
